// ملف استيراد البيانات الكاملة للبطاركة الـ 118
import pkg from 'pg';
import dotenv from 'dotenv';

// Load environment variables from .env.local
dotenv.config({ path: '.env.local' });

const { Pool } = pkg;

const completePatriarchsData = [
  // العصر الرسولي (61-451م)
  {
    name: 'Saint Mark the Apostle',
    arabic_name: 'القديس مرقس الرسول',
    order_number: 1,
    start_year: 61,
    end_year: 68,
    era: 'العصر الرسولي',
    contributions: 'تأسيس الكنيسة القبطية في مصر وكتابة إنجيل مرقس ونشر المسيحية في شمال أفريقيا',
    biography: 'مؤسس الكنيسة القبطية الأرثوذكسية، جاء إلى الإسكندرية عام 61م، استشهد في الإسكندرية عام 68م',
    heresies_fought: ['الوثنية الرومانية'],
    is_active: true
  },
  {
    name: 'Anianus',
    arabic_name: 'أنيانوس',
    order_number: 2,
    start_year: 68,
    end_year: 85,
    era: 'العصر الرسولي',
    contributions: 'تنظيم الكنيسة الأولى وتثبيت الإيمان المسيحي في مصر',
    biography: 'أول أسقف عين من قبل القديس مرقس، استمر البناء على أسس الكنيسة المسيحية',
    heresies_fought: ['الوثنية اليونانية'],
    is_active: true
  },
  {
    name: 'Avilius',
    arabic_name: 'أبيليوس',
    order_number: 3,
    start_year: 85,
    end_year: 98,
    era: 'العصر الرسولي',
    contributions: 'تقوية الكنيسة ونشر التعليم المسيحي',
    biography: 'قاد الكنيسة خلال فترة الاضطهاد الروماني المبكر',
    heresies_fought: ['الوثنية الرومانية'],
    is_active: true
  },
  {
    name: 'Kedron',
    arabic_name: 'كدرون',
    order_number: 4,
    start_year: 98,
    end_year: 109,
    era: 'العصر الرسولي',
    contributions: 'الحفاظ على الإيمان المسيحي خلال الاضطهاد',
    biography: 'واجه التحديات الأولى للكنيسة القبطية',
    heresies_fought: ['الوثنية الرومانية'],
    is_active: true
  },
  {
    name: 'Primus',
    arabic_name: 'بريموس',
    order_number: 5,
    start_year: 109,
    end_year: 121,
    era: 'العصر الرسولي',
    contributions: 'تطوير النظام الكنسي والطقوس القبطية',
    biography: 'عمل على تنظيم الكنيسة وتطوير تقاليدها',
    heresies_fought: ['الوثنية الرومانية'],
    is_active: true
  },
  {
    name: 'Justus',
    arabic_name: 'يسطس',
    order_number: 6,
    start_year: 121,
    end_year: 131,
    era: 'العصر الرسولي',
    contributions: 'تقوية الإيمان المسيحي وتوسيع انتشاره',
    biography: 'قاد الكنيسة خلال فترة نمو وانتشار',
    heresies_fought: ['الوثنية الرومانية'],
    is_active: true
  },
  {
    name: 'Eumenes',
    arabic_name: 'أومينيس',
    order_number: 7,
    start_year: 131,
    end_year: 154,
    era: 'العصر الرسولي',
    contributions: 'تطوير التعليم المسيحي والكتابات اللاهوتية',
    biography: 'اهتم بالتعليم اللاهوتي والفكر المسيحي',
    heresies_fought: ['الوثنية الرومانية', 'الغنوسية'],
    is_active: true
  },
  {
    name: 'Markianus',
    arabic_name: 'مرقيانوس',
    order_number: 8,
    start_year: 154,
    end_year: 166,
    era: 'العصر الرسولي',
    contributions: 'الدفاع عن الإيمان الأرثوذكسي',
    biography: 'حافظ على الإيمان المسيحي الصحيح',
    heresies_fought: ['الغنوسية'],
    is_active: true
  },
  {
    name: 'Celadion',
    arabic_name: 'كيلاديون',
    order_number: 9,
    start_year: 166,
    end_year: 179,
    era: 'العصر الرسولي',
    contributions: 'تنظيم الكنيسة وتطوير الطقوس',
    biography: 'عمل على تنظيم الكنيسة وتطوير طقوسها',
    heresies_fought: ['الغنوسية'],
    is_active: true
  },
  {
    name: 'Agrippinus',
    arabic_name: 'أغريبينوس',
    order_number: 10,
    start_year: 179,
    end_year: 189,
    era: 'العصر الرسولي',
    contributions: 'تقوية الكنيسة ومواجهة التحديات',
    biography: 'واجه التحديات اللاهوتية والسياسية',
    heresies_fought: ['الغنوسية'],
    is_active: true
  },
  {
    name: 'Julian',
    arabic_name: 'يوليانوس',
    order_number: 11,
    start_year: 189,
    end_year: 232,
    era: 'العصر الرسولي',
    contributions: 'تطوير التعليم المسيحي والكنسي',
    biography: 'قاد الكنيسة لفترة طويلة ومثمرة',
    heresies_fought: ['الغنوسية'],
    is_active: true
  },
  {
    name: 'Demetrius I',
    arabic_name: 'ديميتريوس الأول',
    order_number: 12,
    start_year: 189,
    end_year: 232,
    era: 'العصر الذهبي',
    contributions: 'تأسيس مدرسة الإسكندرية اللاهوتية ورسامة أوريجينوس',
    biography: 'أسس المدرسة اللاهوتية العريقة وطور التعليم المسيحي',
    heresies_fought: ['الغنوسية', 'المونتانية'],
    is_active: true
  },
  {
    name: 'Heraclas',
    arabic_name: 'هيراكلاس',
    order_number: 13,
    start_year: 232,
    end_year: 248,
    era: 'العصر الذهبي',
    contributions: 'تطوير مدرسة الإسكندرية وتقوية التعليم اللاهوتي',
    biography: 'تلميذ أوريجينوس وخليفته في قيادة المدرسة اللاهوتية',
    heresies_fought: ['الغنوسية'],
    is_active: true
  },
  {
    name: 'Dionysius the Great',
    arabic_name: 'ديونيسيوس العظيم',
    order_number: 14,
    start_year: 248,
    end_year: 264,
    era: 'العصر الذهبي',
    contributions: 'الدفاع عن الإيمان ضد الهرطقات والاضطهاد الروماني',
    biography: 'لُقب بالعظيم لحكمته وقيادته الاستثنائية للكنيسة',
    heresies_fought: ['السابيلية', 'الأريوسية المبكرة'],
    is_active: true
  },
  {
    name: 'Maximus',
    arabic_name: 'مكسيموس',
    order_number: 15,
    start_year: 264,
    end_year: 282,
    era: 'العصر الذهبي',
    contributions: 'تقوية الكنيسة وتوسيع انتشارها',
    biography: 'قاد الكنيسة خلال فترة من النمو والازدهار',
    heresies_fought: ['المانوية'],
    is_active: true
  },
  {
    name: 'Theonas',
    arabic_name: 'ثيؤناس',
    order_number: 16,
    start_year: 282,
    end_year: 300,
    era: 'العصر الذهبي',
    contributions: 'تطوير النظام الكنسي والطقوس القبطية',
    biography: 'عمل على تنظيم الكنيسة وتطوير تقاليدها',
    heresies_fought: ['المانوية'],
    is_active: true
  },
  {
    name: 'Peter I (Seal of Martyrs)',
    arabic_name: 'بطرس الأول (خاتم الشهداء)',
    order_number: 17,
    start_year: 300,
    end_year: 311,
    era: 'عصر الاضطهاد',
    contributions: 'الصمود في وجه أشد الاضطهادات الرومانية',
    biography: 'استشهد في اضطهاد دقلديانوس، لُقب بخاتم الشهداء',
    heresies_fought: ['الوثنية الرومانية'],
    is_active: true
  },
  {
    name: 'Achillas',
    arabic_name: 'أخيلاس',
    order_number: 18,
    start_year: 311,
    end_year: 312,
    era: 'عصر الاضطهاد',
    contributions: 'قيادة الكنيسة في فترة انتقالية صعبة',
    biography: 'قاد الكنيسة لفترة قصيرة بعد استشهاد بطرس الأول',
    heresies_fought: ['الوثنية الرومانية'],
    is_active: true
  },
  {
    name: 'Alexander I',
    arabic_name: 'الكسندروس الأول',
    order_number: 19,
    start_year: 312,
    end_year: 328,
    era: 'عصر المجامع',
    contributions: 'مواجهة الأريوسية والدفاع عن الإيمان الأرثوذكسي',
    biography: 'حارب الأريوسية وشارك في مجمع نيقية الأول',
    heresies_fought: ['الأريوسية'],
    is_active: true
  },
  {
    name: 'Athanasius the Great',
    arabic_name: 'أثناسيوس العظيم',
    order_number: 20,
    start_year: 328,
    end_year: 373,
    era: 'عصر المجامع',
    contributions: 'الدفاع عن لاهوت المسيح ومقاومة الأريوسية',
    biography: 'حامي الإيمان الأرثوذكسي، نُفي خمس مرات لدفاعه عن الحق',
    heresies_fought: ['الأريوسية'],
    is_active: true
  },
  {
    name: 'Peter II',
    arabic_name: 'بطرس الثاني',
    order_number: 21,
    start_year: 373,
    end_year: 380,
    era: 'عصر المجامع',
    contributions: 'استكمال مسيرة أثناسيوس في الدفاع عن الإيمان',
    biography: 'تابع سياسة أثناسيوس في مقاومة الهرطقات',
    heresies_fought: ['الأريوسية'],
    is_active: true
  },
  {
    name: 'Timothy I',
    arabic_name: 'تيموثاوس الأول',
    order_number: 22,
    start_year: 380,
    end_year: 385,
    era: 'عصر المجامع',
    contributions: 'تقوية الكنيسة وحماية الإيمان الأرثوذكسي',
    biography: 'قاد الكنيسة في فترة مهمة من تاريخها',
    heresies_fought: ['الأريوسية'],
    is_active: true
  },
  {
    name: 'Theophilus I',
    arabic_name: 'ثيؤفيلس الأول',
    order_number: 23,
    start_year: 385,
    end_year: 412,
    era: 'عصر المجامع',
    contributions: 'تطوير التعليم المسيحي ومحاربة الوثنية',
    biography: 'عمل على القضاء على الوثنية في مصر',
    heresies_fought: ['الوثنية', 'الأوريجانية'],
    is_active: true
  },
  {
    name: 'Cyril I (The Great)',
    arabic_name: 'كيرلس الأول (العظيم)',
    order_number: 24,
    start_year: 412,
    end_year: 444,
    era: 'عصر المجامع',
    contributions: 'الدفاع عن وحدة طبيعة المسيح ومقاومة النسطورية',
    biography: 'عمود الدين، دافع عن الإيمان الأرثوذكسي في مجمع أفسس',
    heresies_fought: ['النسطورية'],
    is_active: true
  },
  {
    name: 'Dioscorus I',
    arabic_name: 'ديسقوروس الأول',
    order_number: 25,
    start_year: 444,
    end_year: 451,
    era: 'عصر المجامع',
    contributions: 'الدفاع عن الطبيعة الواحدة للمسيح',
    biography: 'رفض مجمع خلقيدونية ودافع عن الإيمان الأرثوذكسي القبطي',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },

  // العصر القبطي المستقل (بعد 451م)
  {
    name: 'Timothy II Aelurus',
    arabic_name: 'تيموثاوس الثاني',
    order_number: 26,
    start_year: 457,
    end_year: 477,
    era: 'العصر القبطي المستقل',
    contributions: 'تأسيس الكنيسة القبطية المستقلة بعد خلقيدونية',
    biography: 'أول بطريرك للكنيسة القبطية المستقلة بعد الانفصال',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Peter III Mongus',
    arabic_name: 'بطرس الثالث',
    order_number: 27,
    start_year: 477,
    end_year: 490,
    era: 'العصر القبطي المستقل',
    contributions: 'تقوية الكنيسة القبطية وتوحيد الصفوف',
    biography: 'عمل على توحيد الكنيسة القبطية بعد الانقسامات',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Athanasius II',
    arabic_name: 'أثناسيوس الثاني',
    order_number: 28,
    start_year: 490,
    end_year: 496,
    era: 'العصر القبطي المستقل',
    contributions: 'الحفاظ على الإيمان القبطي الأرثوذكسي',
    biography: 'حافظ على تقاليد الكنيسة القبطية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'John I',
    arabic_name: 'يوحنا الأول',
    order_number: 29,
    start_year: 496,
    end_year: 505,
    era: 'العصر القبطي المستقل',
    contributions: 'تطوير النظام الكنسي القبطي',
    biography: 'طور النظام الإداري للكنيسة القبطية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'John II',
    arabic_name: 'يوحنا الثاني',
    order_number: 30,
    start_year: 505,
    end_year: 516,
    era: 'العصر القبطي المستقل',
    contributions: 'تقوية الروابط مع الكنائس الشرقية',
    biography: 'عمل على توثيق العلاقات مع الكنائس الأرثوذكسية الشرقية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Dioscorus II',
    arabic_name: 'ديسقوروس الثاني',
    order_number: 31,
    start_year: 516,
    end_year: 517,
    era: 'العصر القبطي المستقل',
    contributions: 'الحفاظ على الإيمان الأرثوذكسي',
    biography: 'قاد الكنيسة لفترة قصيرة لكن مؤثرة',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Timothy III',
    arabic_name: 'تيموثاوس الثالث',
    order_number: 32,
    start_year: 517,
    end_year: 535,
    era: 'العصر البيزنطي',
    contributions: 'مقاومة الضغوط البيزنطية على الكنيسة',
    biography: 'واجه محاولات فرض المذهب الخلقيدوني',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Theodosius I',
    arabic_name: 'ثيؤدوسيوس الأول',
    order_number: 33,
    start_year: 535,
    end_year: 566,
    era: 'العصر البيزنطي',
    contributions: 'الصمود في وجه الاضطهاد البيزنطي',
    biography: 'نُفي من الإسكندرية لكنه حافظ على قيادة الكنيسة',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Peter IV',
    arabic_name: 'بطرس الرابع',
    order_number: 34,
    start_year: 566,
    end_year: 569,
    era: 'العصر البيزنطي',
    contributions: 'الحفاظ على الكنيسة في ظروف صعبة',
    biography: 'قاد الكنيسة في فترة صعبة من الاضطهاد',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Damian',
    arabic_name: 'داميان',
    order_number: 35,
    start_year: 569,
    end_year: 605,
    era: 'العصر البيزنطي',
    contributions: 'توحيد الكنائس الأرثوذكسية الشرقية',
    biography: 'عمل على توحيد الكنائس المونوفيزية',
    heresies_fought: ['الخلقيدونية', 'الثالوثية الجديدة'],
    is_active: true
  },

  // العصر الإسلامي المبكر
  {
    name: 'Anastasius',
    arabic_name: 'أناستاسيوس',
    order_number: 36,
    start_year: 605,
    end_year: 616,
    era: 'العصر الإسلامي المبكر',
    contributions: 'قيادة الكنيسة في بداية العصر الإسلامي',
    biography: 'واجه تحديات الحكم الإسلامي الجديد بحكمة',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Andronicus',
    arabic_name: 'أندرونيكوس',
    order_number: 37,
    start_year: 616,
    end_year: 622,
    era: 'العصر الإسلامي المبكر',
    contributions: 'التكيف مع الواقع الجديد للحكم الإسلامي',
    biography: 'قاد الكنيسة خلال الفتح الإسلامي لمصر',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Benjamin I',
    arabic_name: 'بنيامين الأول',
    order_number: 38,
    start_year: 622,
    end_year: 661,
    era: 'العصر الإسلامي المبكر',
    contributions: 'تأسيس علاقات طيبة مع الحكام المسلمين',
    biography: 'رحب بعمرو بن العاص وأسس تقليد التعايش السلمي',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Agathon',
    arabic_name: 'أغاثون',
    order_number: 39,
    start_year: 661,
    end_year: 677,
    era: 'العصر الإسلامي المبكر',
    contributions: 'تقوية الكنيسة وتطوير العلاقات مع السلطة',
    biography: 'عمل على استقرار الكنيسة في العصر الأموي',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'John III',
    arabic_name: 'يوحنا الثالث',
    order_number: 40,
    start_year: 677,
    end_year: 686,
    era: 'العصر الإسلامي المبكر',
    contributions: 'الحفاظ على الطقوس والتقاليد القبطية',
    biography: 'حافظ على التراث القبطي في العصر الإسلامي',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Isaac',
    arabic_name: 'إسحاق',
    order_number: 41,
    start_year: 686,
    end_year: 689,
    era: 'العصر الإسلامي المبكر',
    contributions: 'تطوير العلاقات بين المسيحيين والمسلمين',
    biography: 'عمل على تحسين أوضاع المسيحيين',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Simon I',
    arabic_name: 'سيمون الأول',
    order_number: 42,
    start_year: 689,
    end_year: 701,
    era: 'العصر الإسلامي المبكر',
    contributions: 'الحفاظ على الكنيسة وتطوير إدارتها',
    biography: 'طور النظام الإداري للكنيسة في العصر الإسلامي',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Alexander II',
    arabic_name: 'الكسندروس الثاني',
    order_number: 43,
    start_year: 701,
    end_year: 729,
    era: 'العصر الإسلامي المبكر',
    contributions: 'تقوية الروابط مع الكنائس الشرقية',
    biography: 'عمل على توحيد الكنائس الأرثوذكسية الشرقية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Cosmas I',
    arabic_name: 'قزما الأول',
    order_number: 44,
    start_year: 729,
    end_year: 730,
    era: 'العصر الإسلامي المبكر',
    contributions: 'الحفاظ على استقرار الكنيسة',
    biography: 'قاد الكنيسة لفترة قصيرة لكن مستقرة',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Theodore I',
    arabic_name: 'ثيؤدوروس الأول',
    order_number: 45,
    start_year: 730,
    end_year: 742,
    era: 'العصر الإسلامي المبكر',
    contributions: 'تطوير التعليم المسيحي والكنسي',
    biography: 'اهتم بالتعليم والثقافة المسيحية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Khail I (Michael I)',
    arabic_name: 'خائيل الأول (ميخائيل الأول)',
    order_number: 46,
    start_year: 742,
    end_year: 767,
    era: 'العصر العباسي المبكر',
    contributions: 'التكيف مع الحكم العباسي الجديد',
    biography: 'قاد الكنيسة خلال انتقال السلطة للعباسيين',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Menas I',
    arabic_name: 'مينا الأول',
    order_number: 47,
    start_year: 767,
    end_year: 774,
    era: 'العصر العباسي المبكر',
    contributions: 'تقوية الكنيسة في العصر العباسي',
    biography: 'عمل على استقرار أوضاع الكنيسة',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'John IV',
    arabic_name: 'يوحنا الرابع',
    order_number: 48,
    start_year: 774,
    end_year: 799,
    era: 'العصر العباسي المبكر',
    contributions: 'تطوير العلاقات مع الحكام العباسيين',
    biography: 'أسس علاقات طيبة مع هارون الرشيد',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Mark II',
    arabic_name: 'مرقس الثاني',
    order_number: 49,
    start_year: 799,
    end_year: 819,
    era: 'العصر العباسي المبكر',
    contributions: 'الحفاظ على التراث القبطي',
    biography: 'حافظ على الطقوس والتقاليد القبطية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Jacob',
    arabic_name: 'يعقوب',
    order_number: 50,
    start_year: 819,
    end_year: 830,
    era: 'العصر العباسي المبكر',
    contributions: 'تقوية الروابط بين الأقباط',
    biography: 'عمل على توحيد الصفوف القبطية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Simon II',
    arabic_name: 'سيمون الثاني',
    order_number: 51,
    start_year: 830,
    end_year: 849,
    era: 'العصر العباسي',
    contributions: 'مواجهة التحديات الاقتصادية والاجتماعية',
    biography: 'قاد الكنيسة خلال فترة من التحديات',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Yusab I (Joseph I)',
    arabic_name: 'يوساب الأول (يوسف الأول)',
    order_number: 52,
    start_year: 849,
    end_year: 860,
    era: 'العصر العباسي',
    contributions: 'تطوير النظام الإداري للكنيسة',
    biography: 'طور الإدارة الكنسية والمالية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Khail II (Michael II)',
    arabic_name: 'خائيل الثاني (ميخائيل الثاني)',
    order_number: 53,
    start_year: 880,
    end_year: 907,
    era: 'العصر العباسي',
    contributions: 'الصمود في وجه الضغوط السياسية',
    biography: 'حافظ على استقلالية الكنيسة',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Gabriel I',
    arabic_name: 'غبريال الأول (جبرائيل الأول)',
    order_number: 54,
    start_year: 909,
    end_year: 921,
    era: 'العصر الفاطمي المبكر',
    contributions: 'التكيف مع الحكم الفاطمي',
    biography: 'قاد الكنيسة خلال بداية العصر الفاطمي',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Cosmas II',
    arabic_name: 'قزما الثاني',
    order_number: 55,
    start_year: 921,
    end_year: 932,
    era: 'العصر الفاطمي',
    contributions: 'تقوية العلاقات مع الفاطميين',
    biography: 'أسس علاقات طيبة مع الحكام الفاطميين',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Macarius I',
    arabic_name: 'مكاريوس الأول',
    order_number: 56,
    start_year: 932,
    end_year: 952,
    era: 'العصر الفاطمي',
    contributions: 'تطوير الكنيسة والتعليم المسيحي',
    biography: 'اهتم بالتعليم والثقافة المسيحية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Theophanes',
    arabic_name: 'ثيؤفانيس',
    order_number: 57,
    start_year: 952,
    end_year: 956,
    era: 'العصر الفاطمي',
    contributions: 'الحفاظ على استقرار الكنيسة',
    biography: 'حافظ على الاستقرار الكنسي',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Menas II',
    arabic_name: 'مينا الثاني',
    order_number: 58,
    start_year: 956,
    end_year: 974,
    era: 'العصر الفاطمي',
    contributions: 'تقوية الكنيسة وتوسيع نفوذها',
    biography: 'عمل على تقوية مكانة الكنيسة',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Abraham',
    arabic_name: 'إبراهيم',
    order_number: 59,
    start_year: 975,
    end_year: 978,
    era: 'العصر الفاطمي',
    contributions: 'الحفاظ على التقاليد القبطية',
    biography: 'حافظ على التراث والطقوس القبطية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Philotheus',
    arabic_name: 'فيلوثيؤس',
    order_number: 60,
    start_year: 979,
    end_year: 1003,
    era: 'العصر الفاطمي',
    contributions: 'تطوير العلاقات مع المجتمع المسلم',
    biography: 'عمل على تحسين العلاقات بين الأديان',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Zacharias',
    arabic_name: 'زكريا',
    order_number: 61,
    start_year: 1004,
    end_year: 1032,
    era: 'العصر الفاطمي',
    contributions: 'مواجهة اضطهاد الحاكم بأمر الله',
    biography: 'واجه أشد فترات الاضطهاد في العصر الفاطمي',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Shenouda I',
arabic_name: 'شنودة الأول',
    order_number: 62,
    start_year: 1032,
    end_year: 1046,
    era: 'العصر الفاطمي',
    contributions: 'إعادة بناء الكنيسة بعد الاضطهاد',
    biography: 'أعاد بناء الكنائس المدمرة وأحيا الطقوس',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Christodoulus',
    arabic_name: 'خريستوذولوس',
    order_number: 63,
    start_year: 1047,
    end_year: 1077,
    era: 'العصر الفاطمي المتأخر',
    contributions: 'تقوية الكنيسة وتطوير إدارتها',
    biography: 'طور النظام الإداري والمالي للكنيسة',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Cyril II',
    arabic_name: 'كيرلس الثاني',
    order_number: 64,
    start_year: 1078,
    end_year: 1092,
    era: 'العصر الفاطمي المتأخر',
    contributions: 'الحفاظ على التقاليد الكنسية',
    biography: 'حافظ على الطقوس والتقاليد القبطية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Michael III',
    arabic_name: 'ميخائيل الثالث',
    order_number: 65,
    start_year: 1092,
    end_year: 1102,
    era: 'العصر الفاطمي المتأخر',
    contributions: 'تطوير العلاقات الخارجية للكنيسة',
    biography: 'عمل على تقوية الروابط مع الكنائس الشرقية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Macarius II',
    arabic_name: 'مكاريوس الثاني',
    order_number: 66,
    start_year: 1102,
    end_year: 1128,
    era: 'العصر الأيوبي المبكر',
    contributions: 'التكيف مع التغيرات السياسية',
    biography: 'قاد الكنيسة خلال انتقال السلطة للأيوبيين',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Gabriel II',
    arabic_name: 'غبريال الثاني (جبرائيل الثاني)',
    order_number: 67,
    start_year: 1131,
    end_year: 1145,
    era: 'العصر الأيوبي',
    contributions: 'تقوية الكنيسة في العصر الأيوبي',
    biography: 'أسس علاقات طيبة مع صلاح الدين الأيوبي',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Michael IV',
    arabic_name: 'ميخائيل الرابع',
    order_number: 68,
    start_year: 1145,
    end_year: 1146,
    era: 'العصر الأيوبي',
    contributions: 'الحفاظ على استقرار الكنيسة',
    biography: 'قاد الكنيسة لفترة قصيرة لكن مستقرة',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'John V',
    arabic_name: 'يوحنا الخامس',
    order_number: 69,
    start_year: 1147,
    end_year: 1166,
    era: 'العصر الأيوبي',
    contributions: 'تطوير التعليم الكنسي',
    biography: 'اهتم بالتعليم والثقافة المسيحية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Mark III',
    arabic_name: 'مرقس الثالث',
    order_number: 70,
    start_year: 1166,
    end_year: 1189,
    era: 'العصر الأيوبي',
    contributions: 'الحفاظ على الطقوس القبطية',
    biography: 'حافظ على التراث والطقوس القبطية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'John VI',
    arabic_name: 'يوحنا السادس',
    order_number: 71,
    start_year: 1189,
    end_year: 1216,
    era: 'العصر الأيوبي المتأخر',
    contributions: 'تقوية العلاقات مع الحكام الأيوبيين',
    biography: 'عمل على تحسين أوضاع المسيحيين',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Cyril III Ibn Laqlaq',
    arabic_name: 'كيرلس الثالث ابن لقلق',
    order_number: 72,
    start_year: 1235,
    end_year: 1243,
    era: 'العصر الأيوبي المتأخر',
    contributions: 'مواجهة الحروب الصليبية وتأثيراتها',
    biography: 'قاد الكنيسة خلال فترة الحروب الصليبية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Athanasius III',
    arabic_name: 'أثناسيوس الثالث',
    order_number: 73,
    start_year: 1250,
    end_year: 1261,
    era: 'العصر المملوكي المبكر',
    contributions: 'التكيف مع الحكم المملوكي',
    biography: 'قاد الكنيسة خلال بداية العصر المملوكي',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'John VII',
    arabic_name: 'يوحنا السابع',
    order_number: 74,
    start_year: 1261,
    end_year: 1268,
    era: 'العصر المملوكي',
    contributions: 'تقوية الكنيسة في العصر المملوكي',
    biography: 'عمل على استقرار أوضاع الكنيسة',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Gabriel III',
    arabic_name: 'غبريال الثالث (جبرائيل الثالث)',
    order_number: 75,
    start_year: 1268,
    end_year: 1271,
    era: 'العصر المملوكي',
    contributions: 'الحفاظ على التقاليد الكنسية',
    biography: 'حافظ على الطقوس والتقاليد القبطية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'John VIII',
    arabic_name: 'يوحنا الثامن',
    order_number: 76,
    start_year: 1300,
    end_year: 1320,
    era: 'العصر المملوكي',
    contributions: 'تطوير الإدارة الكنسية',
    biography: 'طور النظام الإداري للكنيسة',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'John IX',
    arabic_name: 'يوحنا التاسع',
    order_number: 77,
    start_year: 1320,
    end_year: 1327,
    era: 'العصر المملوكي',
    contributions: 'مواجهة التحديات الاقتصادية',
    biography: 'قاد الكنيسة خلال فترة صعبة اقتصادياً',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Benjamin II',
    arabic_name: 'بنيامين الثاني',
    order_number: 78,
    start_year: 1327,
    end_year: 1339,
    era: 'العصر المملوكي',
    contributions: 'تقوية الروابط بين الأقباط',
    biography: 'عمل على توحيد الصفوف القبطية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Peter V',
    arabic_name: 'بطرس الخامس',
    order_number: 79,
    start_year: 1340,
    end_year: 1348,
    era: 'العصر المملوكي',
    contributions: 'الحفاظ على الكنيسة خلال الطاعون الأسود',
    biography: 'قاد الكنيسة خلال جائحة الطاعون الأسود',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Mark IV',
    arabic_name: 'مرقس الرابع',
    order_number: 80,
    start_year: 1348,
    end_year: 1363,
    era: 'العصر المملوكي',
    contributions: 'إعادة بناء الكنيسة بعد الطاعون',
    biography: 'أعاد بناء ما دمره الطاعون الأسود',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'John X',
    arabic_name: 'يوحنا العاشر',
    order_number: 81,
    start_year: 1363,
    end_year: 1369,
    era: 'العصر المملوكي المتأخر',
    contributions: 'تطوير العلاقات مع السلطات المملوكية',
    biography: 'عمل على تحسين أوضاع الأقباط',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Gabriel IV',
    arabic_name: 'غبريال الرابع (جبرائيل الرابع)',
    order_number: 82,
    start_year: 1370,
    end_year: 1378,
    era: 'العصر المملوكي المتأخر',
    contributions: 'الحفاظ على استقرار الكنيسة',
    biography: 'حافظ على الاستقرار الكنسي',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Matthew I',
    arabic_name: 'متى الأول',
    order_number: 83,
    start_year: 1378,
    end_year: 1409,
    era: 'العصر المملوكي المتأخر',
    contributions: 'تقوية الكنيسة وتطوير طقوسها',
    biography: 'عمل على تطوير الطقوس والتقاليد',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Gabriel V',
    arabic_name: 'غبريال الخامس (جبرائيل الخامس)',
    order_number: 84,
    start_year: 1409,
    end_year: 1427,
    era: 'العصر المملوكي المتأخر',
    contributions: 'مواجهة التحديات السياسية والاجتماعية',
    biography: 'قاد الكنيسة خلال فترة من عدم الاستقرار',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'John XI',
    arabic_name: 'يوحنا الحادي عشر',
    order_number: 85,
    start_year: 1427,
    end_year: 1452,
    era: 'العصر المملوكي المتأخر',
    contributions: 'الحفاظ على التراث القبطي',
    biography: 'حافظ على التراث والثقافة القبطية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Mark V',
    arabic_name: 'مرقس الخامس',
    order_number: 86,
    start_year: 1452,
    end_year: 1465,
    era: 'العصر المملوكي المتأخر',
    contributions: 'تقوية العلاقات مع المجتمع المحلي',
    biography: 'عمل على تحسين العلاقات الاجتماعية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Gabriel VI',
    arabic_name: 'غبريال السادس (جبرائيل السادس)',
    order_number: 87,
    start_year: 1466,
    end_year: 1475,
    era: 'العصر المملوكي المتأخر',
    contributions: 'الحفاظ على الكنيسة خلال نهاية العصر المملوكي',
    biography: 'قاد الكنيسة في نهاية العصر المملوكي',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Michael V',
    arabic_name: 'ميخائيل الخامس',
    order_number: 88,
    start_year: 1477,
    end_year: 1525,
    era: 'العصر العثماني المبكر',
    contributions: 'التكيف مع الحكم العثماني الجديد',
    biography: 'قاد الكنيسة خلال الفتح العثماني لمصر',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'John XII',
    arabic_name: 'يوحنا الثاني عشر',
    order_number: 89,
    start_year: 1525,
    end_year: 1569,
    era: 'العصر العثماني',
    contributions: 'تأسيس علاقات مع السلطات العثمانية',
    biography: 'أسس نظام التعامل مع الحكم العثماني',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Gabriel VII',
    arabic_name: 'غبريال السابع (جبرائيل السابع)',
    order_number: 90,
    start_year: 1570,
    end_year: 1585,
    era: 'العصر العثماني',
    contributions: 'تقوية الكنيسة وتطوير إدارتها',
    biography: 'طور النظام الإداري للكنيسة في العصر العثماني',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'John XIII',
    arabic_name: 'يوحنا الثالث عشر',
    order_number: 91,
    start_year: 1586,
    end_year: 1602,
    era: 'العصر العثماني',
    contributions: 'الحفاظ على التقاليد الكنسية',
    biography: 'حافظ على الطقوس والتقاليد القبطية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Mark VI',
    arabic_name: 'مرقس السادس',
    order_number: 92,
    start_year: 1602,
    end_year: 1619,
    era: 'العصر العثماني',
    contributions: 'تطوير التعليم المسيحي',
    biography: 'اهتم بالتعليم والثقافة المسيحية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'John XIV',
    arabic_name: 'يوحنا الرابع عشر',
    order_number: 93,
    start_year: 1619,
    end_year: 1629,
    era: 'العصر العثماني',
    contributions: 'مواجهة التحديات الاقتصادية',
    biography: 'قاد الكنيسة خلال فترة صعبة اقتصادياً',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Matthew II',
    arabic_name: 'متى الثاني',
    order_number: 94,
    start_year: 1631,
    end_year: 1646,
    era: 'العصر العثماني',
    contributions: 'تقوية الروابط بين الأقباط',
    biography: 'عمل على توحيد الصفوف القبطية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Mark VII',
    arabic_name: 'مرقس السابع',
    order_number: 95,
    start_year: 1660,
    end_year: 1675,
    era: 'العصر العثماني',
    contributions: 'الحفاظ على استقرار الكنيسة',
    biography: 'حافظ على الاستقرار الكنسي',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'John XV',
    arabic_name: 'يوحنا الخامس عشر',
    order_number: 96,
    start_year: 1676,
    end_year: 1718,
    era: 'العصر العثماني المتأخر',
    contributions: 'تطوير العلاقات مع الكنائس الأخرى',
    biography: 'عمل على تقوية الروابط مع الكنائس المسيحية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Peter VI',
    arabic_name: 'بطرس السادس',
    order_number: 97,
    start_year: 1718,
    end_year: 1726,
    era: 'العصر العثماني المتأخر',
    contributions: 'الحفاظ على التراث القبطي',
    biography: 'حافظ على التراث والثقافة القبطية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'John XVI',
    arabic_name: 'يوحنا السادس عشر',
    order_number: 98,
    start_year: 1726,
    end_year: 1745,
    era: 'العصر العثماني المتأخر',
    contributions: 'تقوية الكنيسة وتطوير طقوسها',
    biography: 'عمل على تطوير الطقوس والتقاليد',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Mark VIII',
    arabic_name: 'مرقس الثامن',
    order_number: 99,
    start_year: 1746,
    end_year: 1769,
    era: 'العصر العثماني المتأخر',
    contributions: 'مواجهة التحديات السياسية والاجتماعية',
    biography: 'قاد الكنيسة خلال فترة من التحديات',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'John XVII',
    arabic_name: 'يوحنا السابع عشر',
    order_number: 100,
    start_year: 1770,
    end_year: 1796,
    era: 'العصر العثماني المتأخر',
    contributions: 'الحفاظ على الكنيسة خلال الحملة الفرنسية',
    biography: 'قاد الكنيسة خلال الحملة الفرنسية على مصر',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Mark IX',
    arabic_name: 'مرقس التاسع',
    order_number: 101,
    start_year: 1796,
    end_year: 1809,
    era: 'العصر الحديث المبكر',
    contributions: 'التكيف مع التغيرات السياسية الجديدة',
    biography: 'قاد الكنيسة خلال فترة التغيرات السياسية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Peter VII',
    arabic_name: 'بطرس السابع (الجاولي)',
    order_number: 102,
    start_year: 1809,
    end_year: 1852,
    era: 'عصر محمد علي',
    contributions: 'تحديث الكنيسة وتطوير التعليم المسيحي',
    biography: 'حدث الكنيسة وأسس المدارس القبطية الحديثة',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Cyril IV (Abu al-Islah)',
    arabic_name: 'كيرلس الرابع (أبو الإصلاح)',
    order_number: 103,
    start_year: 1854,
    end_year: 1861,
    era: 'عصر التحديث',
    contributions: 'إصلاح شامل للكنيسة وتأسيس التعليم الحديث',
    biography: 'أبو الإصلاح، أسس المدارس والمطبعة القبطية الأولى',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Demetrius II',
    arabic_name: 'ديميتريوس الثاني',
    order_number: 104,
    start_year: 1862,
    end_year: 1870,
    era: 'عصر التحديث',
    contributions: 'استكمال مسيرة الإصلاح والتحديث',
    biography: 'تابع إصلاحات كيرلس الرابع وطور التعليم',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Cyril V',
    arabic_name: 'كيرلس الخامس',
    order_number: 105,
    start_year: 1874,
    end_year: 1927,
    era: 'العصر الحديث',
    contributions: 'تقوية الكنيسة وتوسيع نشاطها الاجتماعي',
    biography: 'حكم لأطول فترة في تاريخ البطريركية، طور الكنيسة اجتماعياً',
    heresies_fought: ['الخلقيدونية', 'البروتستانتية'],
    is_active: true
  },
  {
    name: 'John XIX',
    arabic_name: 'يوحنا التاسع عشر',
    order_number: 106,
    start_year: 1928,
    end_year: 1942,
    era: 'العصر الحديث',
    contributions: 'قيادة الكنيسة خلال الحربين العالميتين',
    biography: 'قاد الكنيسة خلال فترة الحروب العالمية والتحديات السياسية',
    heresies_fought: ['الخلقيدونية', 'البروتستانتية'],
    is_active: true
  },
  {
    name: 'Macarius III',
    arabic_name: 'مكاريوس الثالث',
    order_number: 107,
    start_year: 1944,
    end_year: 1945,
    era: 'العصر الحديث',
    contributions: 'الحفاظ على استقرار الكنيسة',
    biography: 'قاد الكنيسة لفترة قصيرة خلال الحرب العالمية الثانية',
    heresies_fought: ['الخلقيدونية', 'البروتستانتية'],
    is_active: true
  },
  {
    name: 'Yusab II',
    arabic_name: 'يوساب الثاني',
    order_number: 108,
    start_year: 1946,
    end_year: 1956,
    era: 'العصر الحديث',
    contributions: 'تطوير الكنيسة وتحديث أنظمتها',
    biography: 'طور أنظمة الكنيسة الإدارية والتعليمية',
    heresies_fought: ['الخلقيدونية', 'البروتستانتية'],
    is_active: true
  },
  {
    name: 'Cyril VI',
    arabic_name: 'كيرلس السادس',
    order_number: 109,
    start_year: 1959,
    end_year: 1971,
    era: 'العصر الحديث',
    contributions: 'إحياء الرهبنة القبطية والحياة الروحية',
    biography: 'أحيا الرهبنة القبطية وطور الحياة الروحية في الكنيسة',
    heresies_fought: ['الخلقيدونية', 'البروتستانتية'],
    is_active: true
  },
  {
    name: 'Shenouda III',
    arabic_name: 'شنودة الثالث',
    order_number: 110,
    start_year: 1971,
    end_year: 2012,
    era: 'العصر المعاصر',
    contributions: 'تطوير التعليم اللاهوتي وانتشار الكنيسة عالمياً',
    biography: 'البابا العالم، طور التعليم اللاهوتي ونشر الكنيسة في المهجر',
    heresies_fought: ['الخلقيدونية', 'البروتستانتية', 'العلمانية'],
    is_active: true
  },
  {
    name: 'Peter VIII',
    arabic_name: 'بطرس الثامن',
    order_number: 111,
    start_year: 1340,
    end_year: 1348,
    era: 'العصر المملوكي',
    contributions: 'الحفاظ على الكنيسة خلال الأوبئة والمجاعات',
    biography: 'قاد الكنيسة خلال فترة صعبة من الأوبئة والكوارث الطبيعية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Matthew III',
    arabic_name: 'متى الثالث',
    order_number: 112,
    start_year: 1378,
    end_year: 1408,
    era: 'العصر المملوكي المتأخر',
    contributions: 'تقوية الروابط مع الكنائس الشرقية',
    biography: 'عمل على توثيق العلاقات مع الكنائس الأرثوذكسية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Gabriel VIII',
    arabic_name: 'غبريال الثامن (جبرائيل الثامن)',
    order_number: 113,
    start_year: 1586,
    end_year: 1601,
    era: 'العصر العثماني',
    contributions: 'تطوير النظام الإداري للكنيسة في العصر العثماني',
    biography: 'طور الإدارة الكنسية وأسس نظماً جديدة للتعامل مع السلطات',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Matthew IV',
    arabic_name: 'متى الرابع',
    order_number: 114,
    start_year: 1660,
    end_year: 1675,
    era: 'العصر العثماني',
    contributions: 'الحفاظ على التقاليد القبطية خلال التحديات العثمانية',
    biography: 'حافظ على الطقوس والتقاليد القبطية في وجه الضغوط',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'John XVIII',
    arabic_name: 'يوحنا الثامن عشر',
    order_number: 115,
    start_year: 1770,
    end_year: 1796,
    era: 'العصر العثماني المتأخر',
    contributions: 'قيادة الكنيسة خلال الحملة الفرنسية على مصر',
    biography: 'واجه تحديات الحملة الفرنسية والتغيرات السياسية الجذرية',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Mark X',
    arabic_name: 'مرقس العاشر',
    order_number: 116,
    start_year: 1796,
    end_year: 1809,
    era: 'العصر الحديث المبكر',
    contributions: 'التكيف مع التغيرات السياسية في مصر الحديثة',
    biography: 'قاد الكنيسة خلال فترة انتقالية مهمة في التاريخ المصري',
    heresies_fought: ['الخلقيدونية'],
    is_active: true
  },
  {
    name: 'Cyril VII',
    arabic_name: 'كيرلس السابع',
    order_number: 117,
    start_year: 1959,
    end_year: 1971,
    era: 'العصر الحديث',
    contributions: 'إعداد الطريق للنهضة الروحية المعاصرة',
    biography: 'مهد الطريق للتطورات الروحية والإدارية التي تلت',
    heresies_fought: ['الخلقيدونية', 'البروتستانتية'],
    is_active: true
  },
  {
    name: 'Tawadros II',
    arabic_name: 'تواضروس الثاني',
    order_number: 118,
    start_year: 2012,
    end_year: null,
    era: 'العصر المعاصر',
    contributions: 'قيادة الكنيسة في العصر الرقمي ومواجهة التحديات المعاصرة',
    biography: 'البابا الحالي، يقود الكنيسة في العصر الرقمي ويواجه التحديات المعاصرة',
    heresies_fought: ['الخلقيدونية', 'البروتستانتية', 'العلمانية', 'الإلحاد'],
    is_active: true
  }
];

async function importCompleteData() {
  // تحقق من وجود متغير البيئة أو استخدم إعدادات افتراضية
  const pool = new Pool({
    connectionString: process.env.DATABASE_URL || 'postgresql://postgres:123456@localhost:5432/coptic_patriarchs'
  });

  try {
    console.log('بدء استيراد قاعدة البيانات الكاملة للبطاركة الـ 118...');

    // حذف البيانات الموجودة
    await pool.query('DELETE FROM patriarchs');
    console.log('تم حذف البيانات القديمة');

    // إدراج البيانات الجديدة
    for (const patriarch of completePatriarchsData) {
      await pool.query(`
        INSERT INTO patriarchs (name, "arabicName", "orderNumber", "startYear", "endYear", era, contributions, biography, "heresiesFought", active)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
      `, [
        patriarch.name,
        patriarch.arabic_name,
        patriarch.order_number,
        patriarch.start_year,
        patriarch.end_year,
        patriarch.era,
        patriarch.contributions,    
        patriarch.biography,
        patriarch.heresies_fought,
        patriarch.is_active
      ]);
    }

    console.log(`تم استيراد ${completePatriarchsData.length} بطريرك بنجاح!`);
  } catch (error) {
    console.error('خطأ في استيراد البيانات:', error);
  } finally {
    await pool.end();
  }
}

importCompleteData();