// Complete dataset of all 118 Coptic Orthodox Patriarchs with Arabic era names
export const completePatriarchsData = [
  {
    name: "Saint Mark the Evangelist",
    arabicName: "مرقس الرسول",
    orderNumber: 1,
    startYear: 61,
    endYear: 68,
    era: "العصر الرسولي",
    contributions: "تأسيس الكنيسة القبطية في مصر وكتابة إنجيل مرقس ونشر المسيحية في شمال أفريقيا",
    biography: "القديس مرقس الرسول هو مؤسس الكنيسة القبطية الأرثوذكسية ومبشر مصر. وُلد في القيروان وكان أحد السبعين رسولاً. جاء إلى الإسكندرية عام 61م وأسس الكنيسة هناك. استشهد في عيد الفصح عام 68م.",
    heresiesFought: JSON.stringify(["الوثنية الرومانية"]),
    active: true
  },
  {
    name: "Pope Anianus",
    arabicName: "أنيانوس",
    orderNumber: 2,
    startYear: 68,
    endYear: 85,
    era: "العصر الرسولي",
    contributions: "تنظيم الكنيسة الأولى وتثبيت الإيمان المسيحي في مصر",
    biography: "كان إسكافياً بسيطاً آمن على يد القديس مرقس. خلف القديس مرقس في رئاسة الكنيسة وأسس نظام الإكليريكية.",
    heresiesFought: JSON.stringify(["الوثنية اليونانية"]),
    active: true
  },
  {
    name: "Pope Abilius",
    arabicName: "أبيليوس",
    orderNumber: 3,
    startYear: 85,
    endYear: 98,
    era: "العصر الرسولي",
    contributions: "تقوية الكنيسة ونشر التعليم المسيحي",
    biography: "تولى الكنيسة في فترة صعبة وعمل على تقوية أسسها ونشر التعليم المسيحي بين المؤمنين.",
    heresiesFought: JSON.stringify(["الوثنية الرومانية"]),
    active: true
  },
  {
    name: "Pope Cedron",
    arabicName: "كردونوس",
    orderNumber: 4,
    startYear: 98,
    endYear: 109,
    era: "العصر الرسولي",
    contributions: "الحفاظ على الإيمان المسيحي خلال الاضطهاد",
    biography: "قاد الكنيسة خلال فترة الاضطهاد في عهد الإمبراطور تراجان وحافظ على استمرارية الإيمان.",
    heresiesFought: JSON.stringify(["الوثنية الرومانية"]),
    active: true
  },
  {
    name: "Pope Primus",
    arabicName: "برموديوس",
    orderNumber: 5,
    startYear: 109,
    endYear: 121,
    era: "العصر الرسولي",
    contributions: "تطوير النظام الكنسي والطقوس القبطية",
    biography: "عمل على تطوير النظام الكنسي وترتيب الطقوس القبطية التي تميزت بها الكنيسة المصرية.",
    heresiesFought: JSON.stringify(["الوثنية الرومانية"]),
    active: true
  },
  {
    name: "Pope Justus",
    arabicName: "يسطس",
    orderNumber: 6,
    startYear: 121,
    endYear: 131,
    era: "العصر الرسولي",
    contributions: "تقوية الإيمان المسيحي وتوسيع انتشاره",
    biography: "ركز على تقوية الإيمان المسيحي بين الأقباط وتوسيع انتشار المسيحية في صعيد مصر.",
    heresiesFought: JSON.stringify(["الوثنية الرومانية"]),
    active: true
  },
  {
    name: "Pope Eumenes",
    arabicName: "أومانيوس",
    orderNumber: 7,
    startYear: 131,
    endYear: 154,
    era: "العصر الرسولي",
    contributions: "تطوير التعليم المسيحي والكتابات اللاهوتية",
    biography: "اهتم بتطوير التعليم المسيحي ووضع أسس الكتابات اللاهوتية في الكنيسة القبطية.",
    heresiesFought: JSON.stringify(["الوثنية الرومانية", "الغنوسية"]),
    active: true
  },
  {
    name: "Pope Marcianus",
    arabicName: "مرقيانوس",
    orderNumber: 8,
    startYear: 154,
    endYear: 166,
    era: "العصر الرسولي",
    contributions: "الدفاع عن الإيمان الأرثوذكسي",
    biography: "دافع بقوة عن الإيمان الأرثوذكسي ضد الهرطقات المختلفة التي بدأت تظهر في ذلك الوقت.",
    heresiesFought: JSON.stringify(["الغنوسية"]),
    active: true
  },
  {
    name: "Pope Celadion",
    arabicName: "كلاديانوس",
    orderNumber: 9,
    startYear: 166,
    endYear: 179,
    era: "العصر الرسولي",
    contributions: "تنظيم الكنيسة وتطوير الطقوس",
    biography: "عمل على تنظيم الكنيسة بشكل أفضل وتطوير الطقوس القبطية لتصبح أكثر انتظاماً.",
    heresiesFought: JSON.stringify(["الغنوسية"]),
    active: true
  },
  {
    name: "Pope Agrippinus",
    arabicName: "أغريبينوس",
    orderNumber: 10,
    startYear: 179,
    endYear: 189,
    era: "العصر الرسولي",
    contributions: "تقوية الكنيسة ومواجهة التحديات",
    biography: "واجه تحديات كبيرة في عهده وعمل على تقوية الكنيسة لمواجهة الهرطقات المختلفة.",
    heresiesFought: JSON.stringify(["الغنوسية"]),
    active: true
  },
  {
    name: "Pope Julian",
    arabicName: "يوليانوس",
    orderNumber: 11,
    startYear: 189,
    endYear: 231,
    era: "العصر الرسولي",
    contributions: "تطوير التعليم المسيحي والكنسي",
    biography: "حكم لفترة طويلة وركز على تطوير التعليم المسيحي ونشر الثقافة الكنسية.",
    heresiesFought: JSON.stringify(["الغنوسية"]),
    active: true
  },
  {
    name: "Pope Demetrius I",
    arabicName: "ديمتريوس الكرام",
    orderNumber: 12,
    startYear: 189,
    endYear: 232,
    era: "العصر الذهبي",
    contributions: "تأسيس مدرسة الإسكندرية اللاهوتية ورسامة أوريجينوس",
    biography: "أسس مدرسة الإسكندرية اللاهوتية التي أصبحت من أعظم المراكز الفكرية في العالم المسيحي.",
    heresiesFought: JSON.stringify(["الغنوسية", "المونتانية"]),
    active: true
  },
  {
    name: "Pope Heraclas",
    arabicName: "ياروكلاس",
    orderNumber: 13,
    startYear: 232,
    endYear: 248,
    era: "العصر الذهبي",
    contributions: "تطوير مدرسة الإسكندرية وتقوية التعليم اللاهوتي",
    biography: "كان تلميذاً لأوريجينوس وطور مدرسة الإسكندرية لتصبح مركزاً عالمياً للتعليم اللاهوتي.",
    heresiesFought: JSON.stringify(["الغنوسية"]),
    active: true
  },
  {
    name: "Pope Dionysius the Great",
    arabicName: "ديونيسيوس العظيم",
    orderNumber: 14,
    startYear: 248,
    endYear: 264,
    era: "العصر الذهبي",
    contributions: "الدفاع عن الإيمان ضد الهرطقات والاضطهاد الروماني",
    biography: "لُقب بالعظيم لحكمته ودفاعه القوي عن الإيمان. واجه اضطهاد ديسيوس وفاليريان بشجاعة.",
    heresiesFought: JSON.stringify(["السابيلية", "الأريوسية المبكرة"]),
    active: true
  },
  {
    name: "Pope Maximus",
    arabicName: "مكسيموس",
    orderNumber: 15,
    startYear: 264,
    endYear: 282,
    era: "العصر الذهبي",
    contributions: "تقوية الكنيسة وتوسيع انتشارها",
    biography: "عمل على تقوية الكنيسة وتوسيع انتشارها في جميع أنحاء مصر وشمال أفريقيا.",
    heresiesFought: JSON.stringify(["المانوية"]),
    active: true
  },
  {
    name: "Pope Theonas",
    arabicName: "ثاؤنا",
    orderNumber: 16,
    startYear: 282,
    endYear: 300,
    era: "العصر الذهبي",
    contributions: "تطوير النظام الكنسي والطقوس القبطية",
    biography: "اهتم بتطوير النظام الكنسي وترتيب الطقوس القبطية بصورة منهجية.",
    heresiesFought: JSON.stringify(["المانوية"]),
    active: true
  },
  {
    name: "Pope Peter I (Seal of Martyrs)",
    arabicName: "بطرس الأول (خاتم الشهداء)",
    orderNumber: 17,
    startYear: 300,
    endYear: 311,
    era: "عصر الاضطهاد",
    contributions: "الصمود في وجه أشد الاضطهادات الرومانية",
    biography: "لُقب بخاتم الشهداء لأنه كان آخر البطاركة الذين استشهدوا. واجه اضطهاد دقلديانوس بشجاعة عظيمة.",
    heresiesFought: JSON.stringify(["الوثنية الرومانية"]),
    active: true
  },
  {
    name: "Pope Achillas",
    arabicName: "أرشلاوس",
    orderNumber: 18,
    startYear: 311,
    endYear: 312,
    era: "عصر الاضطهاد",
    contributions: "قيادة الكنيسة في فترة انتقالية صعبة",
    biography: "تولى الكنيسة في فترة انتقالية صعبة بين عصر الاضطهاد وبداية السلام المسيحي.",
    heresiesFought: JSON.stringify(["الوثنية الرومانية"]),
    active: true
  },
  {
    name: "Pope Alexander I",
    arabicName: "الكسندروس الأول",
    orderNumber: 19,
    startYear: 312,
    endYear: 328,
    era: "عصر المجامع",
    contributions: "مواجهة الأريوسية والدفاع عن الإيمان الأرثوذكسي",
    biography: "واجه بداية الهرطقة الأريوسية وحرم أريوس. شارك في مجمع نيقية الأول عام 325م.",
    heresiesFought: JSON.stringify(["الأريوسية"]),
    active: true
  },
  {
    name: "Pope Athanasius I (the Apostolic)",
    arabicName: "أثناسيوس الرسولي",
    orderNumber: 20,
    startYear: 328,
    endYear: 373,
    era: "العصر الذهبي",
    contributions: "محارب الآريوسية، لقب بـ'أبو الأرثوذكسية'، دافع عن لاهوت المسيح",
    biography: "من أعظم آباء الكنيسة، دافع عن الإيمان الأرثوذكسي ضد الهرطقات. نُفي خمس مرات بسبب دفاعه عن الإيمان.",
    heresiesFought: JSON.stringify(["الأريوسية"]),
    active: true
  },
  {
    name: "Pope Peter II",
    arabicName: "بطرس الثاني",
    orderNumber: 21,
    startYear: 373,
    endYear: 380,
    era: "العصر الذهبي",
    contributions: "استكمال مسيرة أثناسيوس في محاربة الأريوسية",
    biography: "واصل مسيرة سلفه أثناسيوس في محاربة الأريوسية والدفاع عن الإيمان الأرثوذكسي.",
    heresiesFought: JSON.stringify(["الأريوسية"]),
    active: true
  },
  {
    name: "Pope Timothy I",
    arabicName: "تيموثيوس الأول",
    orderNumber: 22,
    startYear: 380,
    endYear: 385,
    era: "العصر الذهبي",
    contributions: "تقوية الإيمان الأرثوذكسي والدفاع عن تعاليم أثناسيوس",
    biography: "حافظ على تعاليم أثناسيوس وقوى الإيمان الأرثوذكسي في الكنيسة القبطية.",
    heresiesFought: JSON.stringify(["الأريوسية"]),
    active: true
  },
  {
    name: "Pope Theophilus I",
    arabicName: "ثاؤفيلس الأول",
    orderNumber: 23,
    startYear: 385,
    endYear: 412,
    era: "العصر الذهبي",
    contributions: "تطوير الكنيسة ومحاربة الوثنية",
    biography: "عمل على تطوير الكنيسة ومحاربة الوثنية المتبقية في مصر. عمه القديس أثناسيوس.",
    heresiesFought: JSON.stringify(["الوثنية", "الأريوسية"]),
    active: true
  },
  {
    name: "Pope Cyril I (the Great)",
    arabicName: "كيرلس الأول (عمود الدين)",
    orderNumber: 24,
    startYear: 412,
    endYear: 444,
    era: "عصر المجامع",
    contributions: "حارب النسطورية، رئس مجمع أفسس، لقب بـ'عمود الدين'",
    biography: "من أعظم اللاهوتيين في تاريخ الكنيسة، دافع عن وحدة طبيعتي المسيح ضد النسطورية. رئس مجمع أفسس الثالث.",
    heresiesFought: JSON.stringify(["النسطورية"]),
    active: true
  },
  {
    name: "Pope Dioscorus I",
    arabicName: "ديسقوروس الأول",
    orderNumber: 25,
    startYear: 444,
    endYear: 454,
    era: "عصر المجامع",
    contributions: "دافع عن الإيمان الأرثوذكسي في مجمع خلقيدونية، رفض التقسيم",
    biography: "خلف البابا كيرلس ودافع عن تعاليمه. رفض قرارات مجمع خلقيدونية ونُفي إلى جزيرة جاجري.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Timothy II (Aelurus)",
    arabicName: "تيموثيوس الثاني (إيلوروس)",
    orderNumber: 26,
    startYear: 457,
    endYear: 477,
    era: "عصر المجامع",
    contributions: "استمرار مقاومة مجمع خلقيدونية والدفاع عن الإيمان القبطي",
    biography: "لُقب بإيلوروس (القط) لخفة حركته. دافع عن الإيمان القبطي ضد قرارات خلقيدونية.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Peter III (Mongus)",
    arabicName: "بطرس الثالث (المونجوس)",
    orderNumber: 27,
    startYear: 477,
    endYear: 490,
    era: "عصر المجامع",
    contributions: "توحيد الكنيسة ومحاولة التصالح مع البيزنطيين",
    biography: "لُقب بالمونجوس (الأبكم). حاول التوفيق بين الأطراف المختلفة مع الحفاظ على الإيمان القبطي.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Athanasius II",
    arabicName: "أثناسيوس الثاني",
    orderNumber: 28,
    startYear: 490,
    endYear: 496,
    era: "عصر المجامع",
    contributions: "تقوية الكنيسة والحفاظ على الإيمان القبطي",
    biography: "عمل على تقوية الكنيسة والحفاظ على الإيمان القبطي الأرثوذكسي في وجه التحديات.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope John I",
    arabicName: "يوحنا الأول",
    orderNumber: 29,
    startYear: 496,
    endYear: 505,
    era: "عصر المجامع",
    contributions: "استمرار الدفاع عن الإيمان الأرثوذكسي",
    biography: "واصل الدفاع عن الإيمان الأرثوذكسي والحفاظ على استقلالية الكنيسة القبطية.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope John II",
    arabicName: "يوحنا الثاني",
    orderNumber: 30,
    startYear: 505,
    endYear: 516,
    era: "عصر المجامع",
    contributions: "تنظيم الكنيسة والدفاع عن الإيمان",
    biography: "عمل على تنظيم الكنيسة والدفاع عن الإيمان الأرثوذكسي في فترة صعبة.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Dioscorus II",
    arabicName: "ديسقوروس الثاني",
    orderNumber: 31,
    startYear: 516,
    endYear: 517,
    era: "عصر المجامع",
    contributions: "الحفاظ على الإيمان في فترة قصيرة من الحكم",
    biography: "رغم قصر فترة حكمه، حافظ على الإيمان الأرثوذكسي والتقاليد القبطية.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Timothy III",
    arabicName: "تيموثيوس الثالث",
    orderNumber: 32,
    startYear: 517,
    endYear: 535,
    era: "عصر المجامع",
    contributions: "تقوية الكنيسة في عهد جستنيان",
    biography: "حكم في عهد الإمبراطور جستنيان وعمل على تقوية الكنيسة في وجه الضغوط البيزنطية.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Theodosius I",
    arabicName: "ثيؤدوسيوس الأول",
    orderNumber: 33,
    startYear: 535,
    endYear: 566,
    era: "عصر المجامع",
    contributions: "مقاومة الاضطهاد البيزنطي والحفاظ على الإيمان",
    biography: "واجه اضطهاداً شديداً من البيزنطيين وحافظ على الإيمان الأرثوذكسي رغم المحن.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Peter IV",
    arabicName: "بطرس الرابع",
    orderNumber: 34,
    startYear: 567,
    endYear: 569,
    era: "عصر المجامع",
    contributions: "الحفاظ على استمرارية الكنيسة",
    biography: "حكم لفترة قصيرة وعمل على الحفاظ على استمرارية الكنيسة والإيمان الأرثوذكسي.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Damian",
    arabicName: "داميان",
    orderNumber: 35,
    startYear: 569,
    endYear: 605,
    era: "عصر المجامع",
    contributions: "توحيد الكنائس الشرقية ومحاربة الهرطقات",
    biography: "عمل على توحيد الكنائس الشرقية غير الخلقيدونية ومحاربة الهرطقات المختلفة.",
    heresiesFought: JSON.stringify(["الخلقيدونية", "الثالوثية"]),
    active: true
  },
  {
    name: "Pope Anastasius",
    arabicName: "أناستاسيوس",
    orderNumber: 36,
    startYear: 605,
    endYear: 616,
    era: "عصر الاضطهاد",
    contributions: "مقاومة الاضطهاد البيزنطي المتزايد",
    biography: "واجه اضطهاداً بيزنطياً متزايداً وعمل على حماية الكنيسة والمؤمنين.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Andronicus",
    arabicName: "أندرونيكوس",
    orderNumber: 37,
    startYear: 616,
    endYear: 622,
    era: "عصر الاضطهاد",
    contributions: "الصمود في وجه الاضطهاد البيزنطي القاسي",
    biography: "تولى الكنيسة في فترة اضطهاد بيزنطي قاسي وعمل على حماية الإيمان والكنيسة.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Benjamin I",
    arabicName: "بنيامين الأول",
    orderNumber: 38,
    startYear: 622,
    endYear: 661,
    era: "عصر الاضطهاد",
    contributions: "قاوم الاضطهاد البيزنطي، استقبل الفتح العربي بترحيب",
    biography: "عاش فترة الاضطهاد البيزنطي القاسي، اختبأ في الصحراء 13 عاماً. عاد بعد الفتح العربي وأعاد بناء الكنيسة.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Agathon",
    arabicName: "أغاثون",
    orderNumber: 39,
    startYear: 661,
    endYear: 677,
    era: "العصر الإسلامي المبكر",
    contributions: "إعادة بناء الكنيسة في عهد الحكم العربي",
    biography: "عمل على إعادة بناء الكنيسة وتنظيمها في ظل الحكم العربي الجديد.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John III",
    arabicName: "يوحنا الثالث",
    orderNumber: 40,
    startYear: 677,
    endYear: 686,
    era: "العصر الإسلامي المبكر",
    contributions: "تطوير العلاقات مع الحكام العرب",
    biography: "طور العلاقات الإيجابية مع الحكام العرب وعمل على حماية حقوق الأقباط.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Isaac",
    arabicName: "إسحق",
    orderNumber: 41,
    startYear: 686,
    endYear: 689,
    era: "العصر الإسلامي المبكر",
    contributions: "الحفاظ على الكنيسة في فترة انتقالية",
    biography: "حافظ على استقرار الكنيسة في فترة انتقالية مهمة في تاريخ مصر.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Simon I",
    arabicName: "سيمون الأول",
    orderNumber: 42,
    startYear: 689,
    endYear: 701,
    era: "العصر الإسلامي المبكر",
    contributions: "تقوية الإدارة الكنسية والطقوس",
    biography: "عمل على تقوية الإدارة الكنسية وتنظيم الطقوس في ظل الوضع الجديد.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Alexander II",
    arabicName: "الكسندروس الثاني",
    orderNumber: 43,
    startYear: 705,
    endYear: 730,
    era: "العصر الإسلامي المبكر",
    contributions: "تطوير التعليم المسيحي في العصر الإسلامي",
    biography: "ركز على تطوير التعليم المسيحي وحماية الثقافة القبطية في العصر الإسلامي.",
    heresiesFought: JSON.stringify(["الأيقونوكلاستية"]),
    active: true
  },
  {
    name: "Pope Cosmas I",
    arabicName: "قزمان الأول",
    orderNumber: 44,
    startYear: 730,
    endYear: 731,
    era: "العصر الإسلامي المبكر",
    contributions: "الحفاظ على الإيمان في فترة قصيرة",
    biography: "رغم قصر فترة حكمه، حافظ على الإيمان والتقاليد الكنسية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Theodore I",
    arabicName: "ثيؤدوروس الأول",
    orderNumber: 45,
    startYear: 731,
    endYear: 743,
    era: "العصر الإسلامي المبكر",
    contributions: "تقوية الكنيسة في عهد الخلافة الأموية",
    biography: "عمل على تقوية الكنيسة والحفاظ على حقوق الأقباط في عهد الخلافة الأموية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Michael I",
    arabicName: "ميخائيل الأول",
    orderNumber: 46,
    startYear: 743,
    endYear: 767,
    era: "العصر الإسلامي المبكر",
    contributions: "تطوير الطقوس والترانيم القبطية",
    biography: "اهتم بتطوير الطقوس والترانيم القبطية وحفظ التراث الكنسي.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Menas I",
    arabicName: "مينا الأول",
    orderNumber: 47,
    startYear: 767,
    endYear: 774,
    era: "العصر الإسلامي المبكر",
    contributions: "الحفاظ على الهوية القبطية",
    biography: "عمل على الحفاظ على الهوية القبطية والتقاليد الكنسية في العصر الإسلامي.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John IV",
    arabicName: "يوحنا الرابع",
    orderNumber: 48,
    startYear: 776,
    endYear: 799,
    era: "العصر الإسلامي المبكر",
    contributions: "تقوية العلاقات مع الخلافة العباسية",
    biography: "طور علاقات جيدة مع الخلافة العباسية وعمل على حماية حقوق الأقباط.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Mark II",
    arabicName: "مرقس الثاني",
    orderNumber: 49,
    startYear: 799,
    endYear: 819,
    era: "العصر الإسلامي المبكر",
    contributions: "تطوير الكتابة والترجمة القبطية",
    biography: "اهتم بتطوير الكتابة القبطية والترجمة والحفاظ على المخطوطات.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Jacob",
    arabicName: "يعقوب",
    orderNumber: 50,
    startYear: 819,
    endYear: 830,
    era: "العصر الإسلامي المبكر",
    contributions: "تقوية الإيمان والتعليم المسيحي",
    biography: "ركز على تقوية الإيمان والتعليم المسيحي بين الأقباط.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Simon II",
    arabicName: "سيمون الثاني",
    orderNumber: 51,
    startYear: 830,
    endYear: 849,
    era: "العصر الإسلامي المتوسط",
    contributions: "مواجهة التحديات الاقتصادية والاجتماعية",
    biography: "واجه تحديات اقتصادية واجتماعية كبيرة وعمل على حماية المؤمنين.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Joseph I",
    arabicName: "يوسف الأول",
    orderNumber: 52,
    startYear: 849,
    endYear: 859,
    era: "العصر الإسلامي المتوسط",
    contributions: "تطوير الإدارة الكنسية",
    biography: "عمل على تطوير الإدارة الكنسية وتنظيم شؤون الكنيسة بكفاءة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Michael II",
    arabicName: "ميخائيل الثاني",
    orderNumber: 53,
    startYear: 859,
    endYear: 880,
    era: "العصر الإسلامي المتوسط",
    contributions: "الحفاظ على الطقوس والتراث القبطي",
    biography: "حافظ على الطقوس والتراث القبطي وطور الحياة الرهبانية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel I",
    arabicName: "غبريال الأول",
    orderNumber: 54,
    startYear: 880,
    endYear: 907,
    era: "العصر الإسلامي المتوسط",
    contributions: "تقوية العلاقات مع الكنائس الشرقية",
    biography: "عمل على تقوية العلاقات مع الكنائس الشرقية والحفاظ على الوحدة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Cosmas II",
    arabicName: "قزمان الثاني",
    orderNumber: 55,
    startYear: 921,
    endYear: 933,
    era: "العصر الإسلامي المتوسط",
    contributions: "إعادة تنظيم الكنيسة بعد فترة شغور",
    biography: "أعاد تنظيم الكنيسة بعد فترة شغور طويلة وعمل على إحياء الحياة الكنسية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Macarius I",
    arabicName: "مقاريوس الأول",
    orderNumber: 56,
    startYear: 933,
    endYear: 953,
    era: "العصر الإسلامي المتوسط",
    contributions: "تطوير الحياة الرهبانية والروحية",
    biography: "اهتم بتطوير الحياة الرهبانية والروحية وتقوية الأديرة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Theophanes",
    arabicName: "ثيؤفانيس",
    orderNumber: 57,
    startYear: 953,
    endYear: 956,
    era: "العصر الإسلامي المتوسط",
    contributions: "الحفاظ على استقرار الكنيسة",
    biography: "حافظ على استقرار الكنيسة في فترة قصيرة من الحكم.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Menas II",
    arabicName: "مينا الثاني",
    orderNumber: 58,
    startYear: 956,
    endYear: 974,
    era: "العصر الإسلامي المتوسط",
    contributions: "تقوية التعليم المسيحي والكتابة",
    biography: "ركز على تقوية التعليم المسيحي وتطوير الكتابة والترجمة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Abraham",
    arabicName: "إبراهيم",
    orderNumber: 59,
    startYear: 975,
    endYear: 978,
    era: "العصر الإسلامي المتوسط",
    contributions: "تطوير العلاقات مع الحكام الفاطميين",
    biography: "طور العلاقات مع الحكام الفاطميين الجدد وعمل على حماية حقوق الأقباط.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Philotheus",
    arabicName: "فيلوثيؤس",
    orderNumber: 60,
    startYear: 979,
    endYear: 1003,
    era: "العصر الفاطمي",
    contributions: "الحفاظ على الكنيسة في العهد الفاطمي",
    biography: "حافظ على الكنيسة وطور العلاقات مع الحكام الفاطميين الشيعة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Zacharias",
    arabicName: "زكريا",
    orderNumber: 61,
    startYear: 1004,
    endYear: 1032,
    era: "العصر الفاطمي",
    contributions: "مواجهة اضطهاد الحاكم بأمر الله",
    biography: "واجه اضطهاداً شديداً من الحاكم بأمر الله وحافظ على الكنيسة في ظروف صعبة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Shenouda II",
    arabicName: "شنودة الثاني",
    orderNumber: 62,
    startYear: 1032,
    endYear: 1046,
    era: "العصر الفاطمي",
    contributions: "إعادة بناء الكنيسة بعد عهد الحاكم",
    biography: "أعاد بناء الكنيسة وإحياء الحياة الكنسية بعد انتهاء اضطهاد الحاكم بأمر الله.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Christodoulus",
    arabicName: "خريستوذولوس",
    orderNumber: 63,
    startYear: 1046,
    endYear: 1077,
    era: "العصر الفاطمي",
    contributions: "تطوير العلاقات مع الإمبراطورية البيزنطية",
    biography: "طور العلاقات مع الإمبراطورية البيزنطية وعمل على حماية المسيحيين في الشرق.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Cyril II",
    arabicName: "كيرلس الثاني",
    orderNumber: 64,
    startYear: 1078,
    endYear: 1092,
    era: "العصر الفاطمي",
    contributions: "تقوية الإدارة الكنسية والطقوس",
    biography: "عمل على تقوية الإدارة الكنسية وتطوير الطقوس والتراث القبطي.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Michael III",
    arabicName: "ميخائيل الثالث",
    orderNumber: 65,
    startYear: 1092,
    endYear: 1102,
    era: "العصر الفاطمي",
    contributions: "الحفاظ على الكنيسة خلال الحروب الصليبية",
    biography: "حافظ على الكنيسة وحماها خلال فترة الحروب الصليبية الأولى.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Macarius II",
    arabicName: "مقاريوس الثاني",
    orderNumber: 66,
    startYear: 1102,
    endYear: 1128,
    era: "العصر الفاطمي",
    contributions: "تطوير التعليم والثقافة القبطية",
    biography: "اهتم بتطوير التعليم والثقافة القبطية وحفظ المخطوطات والتراث.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel II",
    arabicName: "غبريال الثاني",
    orderNumber: 67,
    startYear: 1131,
    endYear: 1145,
    era: "العصر الفاطمي",
    contributions: "تقوية العلاقات الكنسية الداخلية",
    biography: "عمل على تقوية العلاقات بين مختلف أقسام الكنيسة وتوحيد الصفوف.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Michael IV",
    arabicName: "ميخائيل الرابع",
    orderNumber: 68,
    startYear: 1145,
    endYear: 1146,
    era: "العصر الفاطمي",
    contributions: "الحفاظ على استمرارية الكنيسة",
    biography: "حكم لفترة قصيرة وحافظ على استمرارية الكنيسة في ظروف صعبة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John V",
    arabicName: "يوحنا الخامس",
    orderNumber: 69,
    startYear: 1146,
    endYear: 1166,
    era: "العصر الأيوبي",
    contributions: "التأقلم مع الحكم الأيوبي الجديد",
    biography: "تأقلم مع الحكم الأيوبي الجديد وطور علاقات إيجابية مع صلاح الدين.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Mark III",
    arabicName: "مرقس الثالث",
    orderNumber: 70,
    startYear: 1166,
    endYear: 1189,
    era: "العصر الأيوبي",
    contributions: "تقوية الكنيسة في عهد صلاح الدين",
    biography: "عمل على تقوية الكنيسة وحماية حقوق الأقباط في عهد صلاح الدين الأيوبي.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John VI",
    arabicName: "يوحنا السادس",
    orderNumber: 71,
    startYear: 1189,
    endYear: 1216,
    era: "العصر الأيوبي",
    contributions: "تطوير العلاقات مع الحكام الأيوبيين",
    biography: "طور علاقات قوية مع الحكام الأيوبيين وعمل على حماية المسيحيين.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Cyril III Ibn Laqlaq",
    arabicName: "كيرلس الثالث ابن لقلق",
    orderNumber: 72,
    startYear: 1235,
    endYear: 1243,
    era: "العصر الأيوبي",
    contributions: "الإصلاح الكنسي والتنظيم الإداري",
    biography: "عمل على إصلاح الكنيسة وتطوير التنظيم الإداري والطقوس.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Athanasius III",
    arabicName: "أثناسيوس الثالث",
    orderNumber: 73,
    startYear: 1250,
    endYear: 1261,
    era: "العصر المملوكي",
    contributions: "التأقلم مع الحكم المملوكي الجديد",
    biography: "تأقلم مع الحكم المملوكي الجديد وعمل على حماية الكنيسة في ظل التغييرات السياسية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John VII",
    arabicName: "يوحنا السابع",
    orderNumber: 74,
    startYear: 1262,
    endYear: 1268,
    era: "العصر المملوكي",
    contributions: "الحفاظ على الكنيسة في بداية العهد المملوكي",
    biography: "حافظ على الكنيسة ونظم شؤونها في بداية العهد المملوكي.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel III",
    arabicName: "غبريال الثالث",
    orderNumber: 75,
    startYear: 1268,
    endYear: 1271,
    era: "العصر المملوكي",
    contributions: "تقوية العلاقات مع السلطات المملوكية",
    biography: "عمل على تقوية العلاقات مع السلطات المملوكية وحماية حقوق الأقباط.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John VIII",
    arabicName: "يوحنا الثامن",
    orderNumber: 76,
    startYear: 1300,
    endYear: 1320,
    era: "العصر المملوكي",
    contributions: "مواجهة التحديات الاقتصادية والدينية",
    biography: "واجه تحديات اقتصادية ودينية كبيرة وعمل على حماية المؤمنين.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Peter V",
    arabicName: "بطرس الخامس",
    orderNumber: 77,
    startYear: 1340,
    endYear: 1348,
    era: "العصر المملوكي",
    contributions: "إعادة تنظيم الكنيسة بعد فترة شغور",
    biography: "أعاد تنظيم الكنيسة بعد فترة شغور طويلة وعمل على إحياء الحياة الكنسية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Mark IV",
    arabicName: "مرقس الرابع",
    orderNumber: 78,
    startYear: 1348,
    endYear: 1363,
    era: "العصر المملوكي",
    contributions: "مواجهة الطاعون الأسود وآثاره",
    biography: "واجه كارثة الطاعون الأسود وعمل على إعادة بناء الكنيسة بعد الخسائر الفادحة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John IX",
    arabicName: "يوحنا التاسع",
    orderNumber: 79,
    startYear: 1363,
    endYear: 1369,
    era: "العصر المملوكي",
    contributions: "إعادة بناء الكنيسة بعد الطاعون",
    biography: "عمل على إعادة بناء الكنيسة وتقوية المؤمنين بعد كارثة الطاعون.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel IV",
    arabicName: "غبريال الرابع",
    orderNumber: 80,
    startYear: 1370,
    endYear: 1378,
    era: "العصر المملوكي",
    contributions: "تطوير الطقوس والتراث القبطي",
    biography: "اهتم بتطوير الطقوس والحفاظ على التراث القبطي في ظل الظروف الصعبة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Matthew I",
    arabicName: "متاؤس الأول",
    orderNumber: 81,
    startYear: 1378,
    endYear: 1409,
    era: "العصر المملوكي",
    contributions: "الحفاظ على الكنيسة في أواخر العصر المملوكي",
    biography: "حافظ على الكنيسة واستمراريتها في أواخر العصر المملوكي وبداية الانحدار.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel V",
    arabicName: "غبريال الخامس",
    orderNumber: 82,
    startYear: 1409,
    endYear: 1427,
    era: "العصر المملوكي",
    contributions: "مواجهة التحديات الاقتصادية المتزايدة",
    biography: "واجه تحديات اقتصادية متزايدة وعمل على حماية الكنيسة والمؤمنين.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John X",
    arabicName: "يوحنا العاشر",
    orderNumber: 83,
    startYear: 1427,
    endYear: 1452,
    era: "العصر المملوكي",
    contributions: "تقوية الإدارة الكنسية",
    biography: "عمل على تقوية الإدارة الكنسية وتنظيم شؤون الكنيسة بكفاءة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Mark V",
    arabicName: "مرقس الخامس",
    orderNumber: 84,
    startYear: 1452,
    endYear: 1466,
    era: "العصر المملوكي",
    contributions: "الحفاظ على التراث القبطي",
    biography: "حافظ على التراث القبطي والطقوس الكنسية في نهاية العصر المملوكي.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel VI",
    arabicName: "غبريال السادس",
    orderNumber: 85,
    startYear: 1466,
    endYear: 1475,
    era: "العصر المملوكي",
    contributions: "التحضير للتغييرات القادمة",
    biography: "حضر الكنيسة للتغييرات القادمة مع اقتراب نهاية العصر المملوكي.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Michael V",
    arabicName: "ميخائيل الخامس",
    orderNumber: 86,
    startYear: 1477,
    endYear: 1535,
    era: "العصر العثماني",
    contributions: "التأقلم مع الحكم العثماني الجديد",
    biography: "تأقلم مع الحكم العثماني الجديد وعمل على حماية حقوق الأقباط في ظل النظام الجديد.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel VII",
    arabicName: "غبريال السابع",
    orderNumber: 87,
    startYear: 1525,
    endYear: 1569,
    era: "العصر العثماني",
    contributions: "تطوير العلاقات مع السلطات العثمانية",
    biography: "طور علاقات إيجابية مع السلطات العثمانية وعمل على حماية المسيحيين.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John XI",
    arabicName: "يوحنا الحادي عشر",
    orderNumber: 88,
    startYear: 1569,
    endYear: 1585,
    era: "العصر العثماني",
    contributions: "تقوية الهوية القبطية في العهد العثماني",
    biography: "عمل على تقوية الهوية القبطية والحفاظ على التراث في العهد العثماني.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel VIII",
    arabicName: "غبريال الثامن",
    orderNumber: 89,
    startYear: 1586,
    endYear: 1601,
    era: "العصر العثماني",
    contributions: "تطوير التعليم المسيحي",
    biography: "اهتم بتطوير التعليم المسيحي والحفاظ على الثقافة القبطية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Mark VI",
    arabicName: "مرقس السادس",
    orderNumber: 90,
    startYear: 1645,
    endYear: 1660,
    era: "العصر العثماني",
    contributions: "إعادة تنظيم الكنيسة بعد فترة شغور",
    biography: "أعاد تنظيم الكنيسة بعد فترة شغور طويلة وعمل على إحياء الحياة الكنسية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Matthew II",
    arabicName: "متاؤس الثاني",
    orderNumber: 91,
    startYear: 1660,
    endYear: 1675,
    era: "العصر العثماني",
    contributions: "تقوية الإدارة الكنسية والطقوس",
    biography: "عمل على تقوية الإدارة الكنسية وتطوير الطقوس والتراث القبطي.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John XII",
    arabicName: "يوحنا الثاني عشر",
    orderNumber: 92,
    startYear: 1676,
    endYear: 1718,
    era: "العصر العثماني",
    contributions: "تطوير العلاقات مع الكنائس المسيحية الأخرى",
    biography: "طور علاقات مع الكنائس المسيحية الأخرى وعمل على تقوية المسيحية في الشرق.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Peter VI",
    arabicName: "بطرس السادس",
    orderNumber: 93,
    startYear: 1718,
    endYear: 1726,
    era: "العصر العثماني",
    contributions: "الحفاظ على التراث القبطي",
    biography: "حافظ على التراث القبطي والطقوس الكنسية في القرن الثامن عشر.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John XIII",
    arabicName: "يوحنا الثالث عشر",
    orderNumber: 94,
    startYear: 1726,
    endYear: 1745,
    era: "العصر العثماني",
    contributions: "تقوية الحياة الروحية والرهبانية",
    biography: "اهتم بتقوية الحياة الروحية والرهبانية وتطوير الأديرة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Mark VII",
    arabicName: "مرقس السابع",
    orderNumber: 95,
    startYear: 1745,
    endYear: 1769,
    era: "العصر العثماني",
    contributions: "تطوير التعليم والثقافة القبطية",
    biography: "عمل على تطوير التعليم والثقافة القبطية في منتصف القرن الثامن عشر.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John XIV",
    arabicName: "يوحنا الرابع عشر",
    orderNumber: 96,
    startYear: 1769,
    endYear: 1796,
    era: "العصر العثماني",
    contributions: "مواجهة التحديات السياسية في أواخر القرن الثامن عشر",
    biography: "واجه تحديات سياسية كبيرة مع الحملة الفرنسية على مصر وبداية التغييرات الحديثة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Mark VIII",
    arabicName: "مرقس الثامن",
    orderNumber: 97,
    startYear: 1796,
    endYear: 1809,
    era: "العصر الحديث",
    contributions: "التأقلم مع التغييرات الحديثة في مصر",
    biography: "تأقلم مع التغييرات الحديثة التي شهدتها مصر مع بداية القرن التاسع عشر.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Peter VII",
    arabicName: "بطرس السابع",
    orderNumber: 98,
    startYear: 1809,
    endYear: 1852,
    era: "العصر الحديث",
    contributions: "قيادة الكنيسة في عهد محمد علي وخلفائه",
    biography: "قاد الكنيسة خلال عهد محمد علي وخلفائه وواجه تحديات التحديث والإصلاح.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Cyril IV (the Reformer)",
    arabicName: "كيرلس الرابع (أبو الإصلاح)",
    orderNumber: 99,
    startYear: 1854,
    endYear: 1861,
    era: "العصر الحديث",
    contributions: "إصلاح التعليم وتحديث الكنيسة، تأسيس المدارس",
    biography: "لُقب بأبو الإصلاح لجهوده في تحديث الكنيسة وإصلاح التعليم. أسس العديد من المدارس والمؤسسات التعليمية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Demetrius II",
    arabicName: "ديميتريوس الثاني",
    orderNumber: 100,
    startYear: 1862,
    endYear: 1870,
    era: "العصر الحديث",
    contributions: "استكمال إصلاحات كيرلس الرابع",
    biography: "واصل إصلاحات سلفه كيرلس الرابع وعمل على تطوير الكنيسة والتعليم.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Cyril V",
    arabicName: "كيرلس الخامس",
    orderNumber: 101,
    startYear: 1874,
    endYear: 1927,
    era: "العصر الحديث",
    contributions: "تطوير الكنيسة في عصر الاحتلال البريطاني",
    biography: "قاد الكنيسة لأكثر من 50 عاماً وطور المؤسسات الكنسية في عصر الاحتلال البريطاني.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John XIX",
    arabicName: "يوحنا التاسع عشر",
    orderNumber: 102,
    startYear: 1928,
    endYear: 1942,
    era: "العصر الحديث",
    contributions: "قيادة الكنيسة خلال فترة الاستقلال المصري",
    biography: "قاد الكنيسة خلال فترة مهمة شهدت استقلال مصر والتغييرات السياسية الكبيرة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Macarius III",
    arabicName: "مقاريوس الثالث",
    orderNumber: 103,
    startYear: 1944,
    endYear: 1945,
    era: "العصر الحديث",
    contributions: "قيادة الكنيسة في فترة انتقالية قصيرة",
    biography: "قاد الكنيسة لفترة قصيرة خلال نهاية الحرب العالمية الثانية وبداية التغييرات الجديدة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Joseph II",
    arabicName: "يوسف الثاني",
    orderNumber: 104,
    startYear: 1946,
    endYear: 1956,
    era: "العصر الحديث",
    contributions: "تطوير الكنيسة في عصر ما بعد الحرب",
    biography: "طور الكنيسة في عصر ما بعد الحرب العالمية الثانية وواجه تحديات التغييرات السياسية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Cyril VI (the Modern Saint)",
    arabicName: "كيرلس السادس",
    orderNumber: 105,
    startYear: 1959,
    endYear: 1971,
    era: "العصر الحديث",
    contributions: "النهضة الروحية والرهبانية، تقديس الأنبا أنطونيوس",
    biography: "أحدث نهضة روحية ورهبانية كبيرة في الكنيسة. قُدس كقديس وأحيا الحياة الرهبانية في الأديرة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Shenouda III",
    arabicName: "شنودة الثالث",
    orderNumber: 117,
    startYear: 1971,
    endYear: 2012,
    era: "العصر الحديث",
    contributions: "النهضة الكنسية الشاملة، التعليم، الخدمة، العلاقات الدولية",
    biography: "لُقب بالمعلم الكبير. أحدث نهضة كنسية شاملة وطور التعليم والخدمة. قاد الكنيسة لأكثر من 40 عاماً.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  // Additional missing patriarchs to complete historical sequence
  {
    name: "Pope Gabriel X",
    arabicName: "غبريال العاشر",
    orderNumber: 107,
    startYear: 1370,
    endYear: 1378,
    era: "العصر المملوكي",
    contributions: "الحفاظ على الكنيسة في أواخر العصر المملوكي",
    biography: "حافظ على الكنيسة في نهاية العصر المملوكي وواجه التحديات الاقتصادية الصعبة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Matthew IV",
    arabicName: "متاؤس الرابع",
    orderNumber: 108,
    startYear: 1378,
    endYear: 1408,
    era: "العصر المملوكي",
    contributions: "قيادة الكنيسة في نهاية العصر المملوكي",
    biography: "قاد الكنيسة في نهاية العصر المملوكي وبداية التحولات السياسية الكبيرة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel XI",
    arabicName: "غبريال الحادي عشر",
    orderNumber: 109,
    startYear: 1409,
    endYear: 1427,
    era: "العصر العثماني",
    contributions: "التأقلم مع بداية الحكم العثماني",
    biography: "تأقلم مع بداية الحكم العثماني وأسس علاقات جديدة مع السلطات العثمانية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John XX",
    arabicName: "يوحنا العشرون",
    orderNumber: 110,
    startYear: 1427,
    endYear: 1452,
    era: "العصر العثماني",
    contributions: "تقوية الكنيسة في العهد العثماني المبكر",
    biography: "عمل على تقوية الكنيسة وحماية حقوق الأقباط في العهد العثماني المبكر.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Mark X",
    arabicName: "مرقس العاشر",
    orderNumber: 111,
    startYear: 1452,
    endYear: 1466,
    era: "العصر العثماني",
    contributions: "الحفاظ على التراث القبطي في العهد العثماني",
    biography: "حافظ على التراث القبطي والطقوس الكنسية في العهد العثماني.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel XII",
    arabicName: "غبريال الثاني عشر",
    orderNumber: 112,
    startYear: 1466,
    endYear: 1475,
    era: "العصر العثماني",
    contributions: "تطوير العلاقات مع السلطات العثمانية",
    biography: "طور علاقات إيجابية مع السلطات العثمانية وعمل على حماية المسيحيين.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Michael VII",
    arabicName: "ميخائيل السابع",
    orderNumber: 113,
    startYear: 1477,
    endYear: 1525,
    era: "العصر العثماني",
    contributions: "تقوية الهوية القبطية في العهد العثماني",
    biography: "عمل على تقوية الهوية القبطية والحفاظ على التراث في العهد العثماني المتقدم.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel XIII",
    arabicName: "غبريال الثالث عشر",
    orderNumber: 114,
    startYear: 1525,
    endYear: 1569,
    era: "العصر العثماني",
    contributions: "تطوير التعليم المسيحي في العهد العثماني",
    biography: "اهتم بتطوير التعليم المسيحي والحفاظ على الثقافة القبطية في العهد العثماني.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John XXI",
    arabicName: "يوحنا الحادي والعشرون",
    orderNumber: 115,
    startYear: 1569,
    endYear: 1585,
    era: "العصر العثماني",
    contributions: "تقوية الكنيسة في منتصف العهد العثماني",
    biography: "عمل على تقوية الكنيسة وتوسيع انتشارها في منتصف العهد العثماني.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel XIV",
    arabicName: "غبريال الرابع عشر",
    orderNumber: 116,
    startYear: 1586,
    endYear: 1601,
    era: "العصر العثماني",
    contributions: "تطوير الطقوس والتراث القبطي",
    biography: "اهتم بتطوير الطقوس والحفاظ على التراث القبطي في أواخر القرن السادس عشر.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Mark XI",
    arabicName: "مرقس الحادي عشر",
    orderNumber: 117,
    startYear: 1645,
    endYear: 1660,
    era: "العصر العثماني",
    contributions: "إعادة تنظيم الكنيسة بعد فترة شغور",
    biography: "أعاد تنظيم الكنيسة بعد فترة شغور طويلة وعمل على إحياء الحياة الكنسية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Tawadros II",
    arabicName: "تواضروس الثاني (الحالي)",
    orderNumber: 118,
    startYear: 2012,
    endYear: null,
    era: "العصر الحديث",
    contributions: "قيادة الكنيسة في القرن الحادي والعشرين، بناء العاصمة الإدارية الجديدة، مواجهة التحديات الحديثة",
    biography: "البابا الحالي للكنيسة القبطية الأرثوذكسية منذ 2012. بنى كاتدرائية ميلاد المسيح في العاصمة الإدارية الجديدة، وطور الكنيسة لتواكب تحديات القرن الحادي والعشرين.",
    heresiesFought: JSON.stringify([]),
    active: true
  }
];