// القائمة الرسمية الكاملة لبطاركة الكنيسة القبطية الأرثوذكسية الـ118
export const completeOfficialPatriarchs = [
  {
    name: "Saint Mark the Evangelist",
    arabicName: "القديس مرقس الرسول",
    orderNumber: 1,
    startYear: 61,
    endYear: 68,
    era: "العصر الرسولي",
    contributions: "تأسيس الكنيسة القبطية في مصر وكتابة إنجيل مرقس ونشر المسيحية في شمال أفريقيا",
    biography: "القديس مرقس الرسول هو مؤسس الكنيسة القبطية الأرثوذكسية ومبشر مصر. وُلد في القيروان وكان أحد السبعين رسولاً. جاء إلى الإسكندرية عام 61م وأسس الكنيسة هناك. استشهد في عيد الفصح عام 68م.",
    heresiesFought: JSON.stringify(["الوثنية الرومانية"]),
    active: true
  },
  {
    name: "Pope Anianus",
    arabicName: "أنيانوس",
    orderNumber: 2,
    startYear: 68,
    endYear: 85,
    era: "العصر الرسولي",
    contributions: "تنظيم الكنيسة الأولى وتثبيت الإيمان المسيحي في مصر",
    biography: "كان إسكافياً بسيطاً آمن على يد القديس مرقس. خلف القديس مرقس في رئاسة الكنيسة وأسس نظام الإكليريكية.",
    heresiesFought: JSON.stringify(["الوثنية اليونانية"]),
    active: true
  },
  {
    name: "Pope Abilius",
    arabicName: "ميليوس",
    orderNumber: 3,
    startYear: 85,
    endYear: 98,
    era: "العصر الرسولي",
    contributions: "تقوية الكنيسة ونشر التعليم المسيحي",
    biography: "تولى الكنيسة في فترة صعبة وعمل على تقوية أسسها ونشر التعليم المسيحي بين المؤمنين.",
    heresiesFought: JSON.stringify(["الوثنية الرومانية"]),
    active: true
  },
  {
    name: "Pope Cedron",
    arabicName: "كردونوس",
    orderNumber: 4,
    startYear: 98,
    endYear: 109,
    era: "العصر الرسولي",
    contributions: "الحفاظ على الإيمان المسيحي خلال الاضطهاد",
    biography: "قاد الكنيسة خلال فترة الاضطهاد في عهد الإمبراطور تراجان وحافظ على استمرارية الإيمان.",
    heresiesFought: JSON.stringify(["الوثنية الرومانية"]),
    active: true
  },
  {
    name: "Pope Primus",
    arabicName: "إبراميوس",
    orderNumber: 5,
    startYear: 109,
    endYear: 121,
    era: "العصر الرسولي",
    contributions: "تطوير النظام الكنسي والطقوس القبطية",
    biography: "عمل على تطوير النظام الكنسي وترتيب الطقوس القبطية التي تميزت بها الكنيسة المصرية.",
    heresiesFought: JSON.stringify(["الوثنية الرومانية"]),
    active: true
  },
  {
    name: "Pope Justus",
    arabicName: "يسطس",
    orderNumber: 6,
    startYear: 121,
    endYear: 131,
    era: "العصر الرسولي",
    contributions: "تقوية الإيمان المسيحي وتوسيع انتشاره",
    biography: "ركز على تقوية الإيمان المسيحي بين الأقباط وتوسيع انتشار المسيحية في صعيد مصر.",
    heresiesFought: JSON.stringify(["الوثنية الرومانية"]),
    active: true
  },
  {
    name: "Pope Eumenes",
    arabicName: "أومانيوس",
    orderNumber: 7,
    startYear: 131,
    endYear: 154,
    era: "العصر الرسولي",
    contributions: "تطوير التعليم المسيحي والكتابات اللاهوتية",
    biography: "اهتم بتطوير التعليم المسيحي ووضع أسس الكتابات اللاهوتية في الكنيسة القبطية.",
    heresiesFought: JSON.stringify(["الوثنية الرومانية", "الغنوسية"]),
    active: true
  },
  {
    name: "Pope Marcianus",
    arabicName: "مرقيانوس",
    orderNumber: 8,
    startYear: 154,
    endYear: 166,
    era: "العصر الرسولي",
    contributions: "الدفاع عن الإيمان الأرثوذكسي",
    biography: "دافع بقوة عن الإيمان الأرثوذكسي ضد الهرطقات المختلفة التي بدأت تظهر في ذلك الوقت.",
    heresiesFought: JSON.stringify(["الغنوسية"]),
    active: true
  },
  {
    name: "Pope Celadion",
    arabicName: "كلاديانوس",
    orderNumber: 9,
    startYear: 166,
    endYear: 179,
    era: "العصر الرسولي",
    contributions: "تنظيم الكنيسة وتطوير الطقوس",
    biography: "عمل على تنظيم الكنيسة بشكل أفضل وتطوير الطقوس القبطية لتصبح أكثر انتظاماً.",
    heresiesFought: JSON.stringify(["الغنوسية"]),
    active: true
  },
  {
    name: "Pope Agrippinus",
    arabicName: "أغريبينوس",
    orderNumber: 10,
    startYear: 179,
    endYear: 189,
    era: "العصر الرسولي",
    contributions: "تقوية الكنيسة ومواجهة التحديات",
    biography: "واجه تحديات كبيرة في عهده وعمل على تقوية الكنيسة لمواجهة الهرطقات المختلفة.",
    heresiesFought: JSON.stringify(["الغنوسية"]),
    active: true
  },
  {
    name: "Pope Julian",
    arabicName: "يوليانوس",
    orderNumber: 11,
    startYear: 189,
    endYear: 232,
    era: "العصر الرسولي",
    contributions: "قيادة الكنيسة لفترة طويلة وتطوير التعليم",
    biography: "حكم لفترة طويلة وركز على تطوير التعليم المسيحي ونشر الثقافة الكنسية.",
    heresiesFought: JSON.stringify(["الغنوسية"]),
    active: true
  },
  {
    name: "Pope Demetrius I",
    arabicName: "ديمتريوس الأول",
    orderNumber: 12,
    startYear: 189,
    endYear: 232,
    era: "العصر الذهبي",
    contributions: "تأسيس مدرسة الإسكندرية اللاهوتية والنهضة الفكرية",
    biography: "أسس مدرسة الإسكندرية اللاهوتية التي أصبحت من أعظم المراكز الفكرية في العالم المسيحي.",
    heresiesFought: JSON.stringify(["الغنوسية", "المونتانية"]),
    active: true
  },
  {
    name: "Pope Heraclas",
    arabicName: "ياراكلاس",
    orderNumber: 13,
    startYear: 232,
    endYear: 248,
    era: "العصر الذهبي",
    contributions: "تطوير مدرسة الإسكندرية ونشر التعليم اللاهوتي",
    biography: "كان من تلاميذ أوريجانوس وطور مدرسة الإسكندرية ونشر التعليم اللاهوتي في أنحاء الإمبراطورية.",
    heresiesFought: JSON.stringify(["الغنوسية"]),
    active: true
  },
  {
    name: "Pope Dionysius the Great",
    arabicName: "ديونيسيوس",
    orderNumber: 14,
    startYear: 248,
    endYear: 265,
    era: "العصر الذهبي",
    contributions: "مواجهة الاضطهاد العظيم ونشر الكرازة",
    biography: "واجه الاضطهاد العظيم في عهد ديكيوس وفاليريان، ونشر الكرازة في أفريقيا وآسيا الصغرى.",
    heresiesFought: JSON.stringify(["السابيلية"]),
    active: true
  },
  {
    name: "Pope Maximus",
    arabicName: "مكسيموس",
    orderNumber: 15,
    startYear: 265,
    endYear: 282,
    era: "العصر الذهبي",
    contributions: "إعادة بناء الكنيسة بعد الاضطهاد",
    biography: "عمل على تقوية الكنيسة وتوسيع انتشارها في جميع أنحاء مصر وشمال أفريقيا.",
    heresiesFought: JSON.stringify(["المانوية"]),
    active: true
  },
  {
    name: "Pope Theonas",
    arabicName: "ثاؤنا",
    orderNumber: 16,
    startYear: 282,
    endYear: 300,
    era: "العصر الذهبي",
    contributions: "إعداد الكنيسة لمواجهة الاضطهاد الأعظم",
    biography: "أعد الكنيسة لمواجهة اضطهاد دقلديانوس وقوى إيمان المؤمنين قبل بداية عصر الشهداء.",
    heresiesFought: JSON.stringify(["المانوية"]),
    active: true
  },
  {
    name: "Pope Peter I (Seal of Martyrs)",
    arabicName: "بطرس الأول",
    orderNumber: 17,
    startYear: 300,
    endYear: 311,
    era: "عصر الاضطهاد",
    contributions: "قيادة الكنيسة خلال الاضطهاد الأعظم والاستشهاد في سبيل الإيمان",
    biography: "لُقب بخاتم الشهداء لأنه كان آخر البطاركة الذين استشهدوا. واجه اضطهاد دقلديانوس بشجاعة عظيمة.",
    heresiesFought: JSON.stringify(["الوثنية الرومانية"]),
    active: true
  },
  {
    name: "Pope Achillas",
    arabicName: "أرشيلاوس",
    orderNumber: 18,
    startYear: 311,
    endYear: 312,
    era: "عصر الاضطهاد",
    contributions: "تهيئة الكنيسة لعصر السلام",
    biography: "حكم لفترة قصيرة وعمل على تهيئة الكنيسة للانتقال من عصر الاضطهاد إلى عصر السلام.",
    heresiesFought: JSON.stringify(["الوثنية الرومانية"]),
    active: true
  },
  {
    name: "Pope Alexander I",
    arabicName: "ألكسندروس الأول",
    orderNumber: 19,
    startYear: 312,
    endYear: 328,
    era: "عصر المجامع",
    contributions: "مواجهة الأريوسية والدفاع عن الإيمان الأرثوذكسي",
    biography: "واجه بداية الهرطقة الأريوسية وحرم أريوس. شارك في مجمع نيقية الأول عام 325م.",
    heresiesFought: JSON.stringify(["الأريوسية"]),
    active: true
  },
  {
    name: "Pope Athanasius I (the Apostolic)",
    arabicName: "أثناسيوس الرسولي",
    orderNumber: 20,
    startYear: 328,
    endYear: 373,
    era: "العصر الذهبي",
    contributions: "محارب الآريوسية، لقب بـ'أبو الأرثوذكسية'، دافع عن لاهوت المسيح",
    biography: "من أعظم آباء الكنيسة، دافع عن الإيمان الأرثوذكسي ضد الهرطقات. نُفي خمس مرات بسبب دفاعه عن الإيمان.",
    heresiesFought: JSON.stringify(["الأريوسية"]),
    active: true
  },
  {
    name: "Pope Peter II",
    arabicName: "بطرس الثاني",
    orderNumber: 21,
    startYear: 373,
    endYear: 380,
    era: "العصر الذهبي",
    contributions: "استكمال مسيرة أثناسيوس في محاربة الأريوسية",
    biography: "واصل مسيرة سلفه أثناسيوس في محاربة الأريوسية والدفاع عن الإيمان الأرثوذكسي.",
    heresiesFought: JSON.stringify(["الأريوسية"]),
    active: true
  },
  {
    name: "Pope Timothy I",
    arabicName: "تيموثاوس الأول",
    orderNumber: 22,
    startYear: 380,
    endYear: 385,
    era: "العصر الذهبي",
    contributions: "تقوية الإيمان الأرثوذكسي والدفاع عن تعاليم أثناسيوس",
    biography: "حافظ على تعاليم أثناسيوس وقوى الإيمان الأرثوذكسي في الكنيسة القبطية.",
    heresiesFought: JSON.stringify(["الأريوسية"]),
    active: true
  },
  {
    name: "Pope Theophilus I",
    arabicName: "ثاوفيلس الأول",
    orderNumber: 23,
    startYear: 385,
    endYear: 412,
    era: "العصر الذهبي",
    contributions: "تطوير الكنيسة ومحاربة الوثنية",
    biography: "عمل على تطوير الكنيسة ومحاربة الوثنية المتبقية في مصر.",
    heresiesFought: JSON.stringify(["الوثنية", "الأريوسية"]),
    active: true
  },
  {
    name: "Pope Cyril I (the Great)",
    arabicName: "كيرلس الأول",
    orderNumber: 24,
    startYear: 412,
    endYear: 444,
    era: "عصر المجامع",
    contributions: "حارب النسطورية، رئس مجمع أفسس، لقب بـ'عمود الدين'",
    biography: "من أعظم اللاهوتيين في تاريخ الكنيسة، دافع عن وحدة طبيعتي المسيح ضد النسطورية.",
    heresiesFought: JSON.stringify(["النسطورية"]),
    active: true
  },
  {
    name: "Pope Dioscorus I",
    arabicName: "ديسقورس الأول",
    orderNumber: 25,
    startYear: 444,
    endYear: 454,
    era: "عصر المجامع",
    contributions: "دافع عن الإيمان الأرثوذكسي في مجمع خلقيدونية",
    biography: "خلف البابا كيرلس ودافع عن تعاليمه. رفض قرارات مجمع خلقيدونية.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Timothy II",
    arabicName: "تيموثاوس الثاني",
    orderNumber: 26,
    startYear: 454,
    endYear: 477,
    era: "عصر المجامع",
    contributions: "مواصلة الدفاع عن الإيمان الأرثوذكسي",
    biography: "واصل الدفاع عن الإيمان الأرثوذكسي ضد قرارات مجمع خلقيدونية.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Peter III",
    arabicName: "بطرس الثالث",
    orderNumber: 27,
    startYear: 477,
    endYear: 490,
    era: "عصر المجامع",
    contributions: "تقوية الكنيسة القبطية والدفاع عن العقيدة",
    biography: "عمل على تقوية الكنيسة القبطية والدفاع عن العقيدة الأرثوذكسية.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Athanasius II",
    arabicName: "أثناسيوس الثاني",
    orderNumber: 28,
    startYear: 490,
    endYear: 496,
    era: "عصر المجامع",
    contributions: "الحفاظ على تراث أثناسيوس الرسولي",
    biography: "حافظ على تراث أثناسيوس الرسولي ودافع عن الإيمان الأرثوذكسي.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope John I",
    arabicName: "يوأنس الأول",
    orderNumber: 29,
    startYear: 496,
    endYear: 505,
    era: "عصر المجامع",
    contributions: "قيادة الكنيسة في ظروف صعبة",
    biography: "قاد الكنيسة في ظروف صعبة وحافظ على وحدة المؤمنين.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope John II",
    arabicName: "يوأنس الثاني",
    orderNumber: 30,
    startYear: 505,
    endYear: 516,
    era: "عصر المجامع",
    contributions: "استمرار مسيرة الدفاع عن الإيمان",
    biography: "واصل مسيرة الدفاع عن الإيمان الأرثوذكسي ضد التحديات المختلفة.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Dioscorus II",
    arabicName: "ديسقورس الثاني",
    orderNumber: 31,
    startYear: 516,
    endYear: 517,
    era: "عصر المجامع",
    contributions: "قيادة قصيرة لكن مؤثرة",
    biography: "حكم لفترة قصيرة لكن ترك أثراً في تقوية الكنيسة.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Timothy III",
    arabicName: "تيموثاوس الثالث",
    orderNumber: 32,
    startYear: 517,
    endYear: 535,
    era: "عصر المجامع",
    contributions: "إعادة تنظيم الكنيسة",
    biography: "عمل على إعادة تنظيم الكنيسة وتقوية أسسها.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Theodosius I",
    arabicName: "ثيودوسيوس الأول",
    orderNumber: 33,
    startYear: 535,
    endYear: 566,
    era: "عصر المجامع",
    contributions: "مقاومة الاضطهاد البيزنطي",
    biography: "قاوم الاضطهاد البيزنطي ودافع عن استقلالية الكنيسة القبطية.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Peter IV",
    arabicName: "بطرس الرابع",
    orderNumber: 34,
    startYear: 567,
    endYear: 569,
    era: "عصر المجامع",
    contributions: "الحفاظ على الاستقرار",
    biography: "عمل على الحفاظ على الاستقرار في الكنيسة في فترة قصيرة.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Damian",
    arabicName: "داميانوس",
    orderNumber: 35,
    startYear: 569,
    endYear: 605,
    era: "عصر المجامع",
    contributions: "تقوية الكنيسة وتوسيع نفوذها",
    biography: "قوى الكنيسة ووسع نفوذها في مختلف أنحاء مصر والنوبة.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Anastasius",
    arabicName: "أنسطاسيوس",
    orderNumber: 36,
    startYear: 605,
    endYear: 616,
    era: "عصر المجامع",
    contributions: "مواجهة التحديات الخارجية",
    biography: "واجه التحديات الخارجية وحافظ على قوة الكنيسة.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Andronicus",
    arabicName: "أندرونيكوس",
    orderNumber: 37,
    startYear: 616,
    endYear: 622,
    era: "عصر المجامع",
    contributions: "قيادة الكنيسة في فترة انتقالية",
    biography: "قاد الكنيسة في فترة انتقالية صعبة مع بداية الفتح الإسلامي.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Benjamin I",
    arabicName: "بنيامين الأول",
    orderNumber: 38,
    startYear: 622,
    endYear: 661,
    era: "عصر المجامع",
    contributions: "استقبال الفتح الإسلامي وحماية الكنيسة",
    biography: "استقبل الفتح الإسلامي وتفاوض مع عمرو بن العاص لحماية الكنيسة والأقباط.",
    heresiesFought: JSON.stringify(["الخلقيدونية"]),
    active: true
  },
  {
    name: "Pope Agathon",
    arabicName: "أغاثون",
    orderNumber: 39,
    startYear: 661,
    endYear: 677,
    era: "العصر الإسلامي",
    contributions: "تأسيس العلاقات مع الحكم الإسلامي",
    biography: "أسس العلاقات مع الحكم الإسلامي وحافظ على حقوق الأقباط.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John III",
    arabicName: "يوأنس الثالث",
    orderNumber: 40,
    startYear: 677,
    endYear: 686,
    era: "العصر الإسلامي",
    contributions: "استمرار التعايش مع الحكم الإسلامي",
    biography: "واصل سياسة التعايش مع الحكم الإسلامي والحفاظ على الهوية القبطية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Isaac",
    arabicName: "إسحق",
    orderNumber: 41,
    startYear: 686,
    endYear: 689,
    era: "العصر الإسلامي",
    contributions: "قيادة قصيرة لكن حكيمة",
    biography: "قاد الكنيسة لفترة قصيرة لكن بحكمة ودراية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Simon I",
    arabicName: "سيمون الأول",
    orderNumber: 42,
    startYear: 689,
    endYear: 701,
    era: "العصر الإسلامي",
    contributions: "تقوية الهوية القبطية",
    biography: "عمل على تقوية الهوية القبطية والحفاظ على التراث الكنسي.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Alexander II",
    arabicName: "ألكسندروس الثاني",
    orderNumber: 43,
    startYear: 701,
    endYear: 704,
    era: "العصر الإسلامي",
    contributions: "مواصلة السياسات الحكيمة",
    biography: "واصل السياسات الحكيمة في التعامل مع السلطات الإسلامية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Cosmas I",
    arabicName: "قسما الأول",
    orderNumber: 44,
    startYear: 704,
    endYear: 730,
    era: "العصر الإسلامي",
    contributions: "تطوير التعليم الكنسي",
    biography: "طور التعليم الكنسي ونشر الثقافة القبطية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Theodore",
    arabicName: "ثيؤدور",
    orderNumber: 45,
    startYear: 730,
    endYear: 743,
    era: "العصر الإسلامي",
    contributions: "الحفاظ على التراث الكنسي",
    biography: "حافظ على التراث الكنسي وطور الأدب القبطي.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Khael I",
    arabicName: "خائيل الأول",
    orderNumber: 46,
    startYear: 743,
    endYear: 767,
    era: "العصر الإسلامي",
    contributions: "تقوية الكنيسة داخلياً",
    biography: "قوى الكنيسة داخلياً وطور النظم الإدارية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Mena I",
    arabicName: "مينا الأول",
    orderNumber: 47,
    startYear: 767,
    endYear: 774,
    era: "العصر الإسلامي",
    contributions: "تعزيز العلاقات مع الأديرة",
    biography: "عزز العلاقات مع الأديرة وطور الحياة الرهبانية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John IV",
    arabicName: "يوأنس الرابع",
    orderNumber: 48,
    startYear: 774,
    endYear: 799,
    era: "العصر الإسلامي",
    contributions: "إدارة حكيمة للكنيسة",
    biography: "أدار الكنيسة بحكمة وحافظ على استقرارها لفترة طويلة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Mark II",
    arabicName: "مرقس الثاني",
    orderNumber: 49,
    startYear: 799,
    endYear: 819,
    era: "العصر الإسلامي",
    contributions: "تطوير الطقوس القبطية",
    biography: "طور الطقوس القبطية وحافظ على تميزها.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Jacob",
    arabicName: "يعقوب",
    orderNumber: 50,
    startYear: 819,
    endYear: 830,
    era: "العصر الإسلامي",
    contributions: "تقوية الوحدة الكنسية",
    biography: "قوى الوحدة الكنسية وحارب الانقسامات.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Simon II",
    arabicName: "سيمون الثاني",
    orderNumber: 51,
    startYear: 830,
    endYear: 849,
    era: "العصر الإسلامي",
    contributions: "مواجهة التحديات الاقتصادية",
    biography: "واجه التحديات الاقتصادية وحافظ على قوة الكنيسة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Yusab I",
    arabicName: "يوساب الأول",
    orderNumber: 52,
    startYear: 849,
    endYear: 859,
    era: "العصر الإسلامي",
    contributions: "تطوير الإدارة الكنسية",
    biography: "طور الإدارة الكنسية ونظم شؤون الأساقفة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Khael II",
    arabicName: "خائيل الثاني",
    orderNumber: 53,
    startYear: 859,
    endYear: 880,
    era: "العصر الإسلامي",
    contributions: "مواجهة التحديات السياسية",
    biography: "واجه التحديات السياسية بحكمة ودبلوماسية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Cosmas II",
    arabicName: "قسما الثاني",
    orderNumber: 54,
    startYear: 880,
    endYear: 903,
    era: "العصر الإسلامي",
    contributions: "إعادة تنظيم الكنيسة",
    biography: "أعاد تنظيم الكنيسة وقوى أسسها الإدارية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Shenouda I",
    arabicName: "شنوده الأول",
    orderNumber: 55,
    startYear: 859,
    endYear: 880,
    era: "العصر الإسلامي",
    contributions: "تطوير التعليم والثقافة",
    biography: "طور التعليم والثقافة القبطية ونشر المعرفة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Michael I",
    arabicName: "ميخائيل الأول",
    orderNumber: 56,
    startYear: 880,
    endYear: 907,
    era: "العصر الإسلامي",
    contributions: "تقوية العلاقات الخارجية",
    biography: "قوى العلاقات الخارجية للكنيسة مع الكنائس الأخرى.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel I",
    arabicName: "غبريال الأول",
    orderNumber: 57,
    startYear: 910,
    endYear: 921,
    era: "العصر الإسلامي",
    contributions: "إحياء التراث الرهباني",
    biography: "أحيا التراث الرهباني وطور الأديرة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Cosmas III",
    arabicName: "قسما الثالث",
    orderNumber: 58,
    startYear: 921,
    endYear: 932,
    era: "العصر الإسلامي",
    contributions: "الحفاظ على الاستقرار",
    biography: "حافظ على الاستقرار في فترة مضطربة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Macarius I",
    arabicName: "مكاريوس الأول",
    orderNumber: 59,
    startYear: 932,
    endYear: 952,
    era: "العصر الإسلامي",
    contributions: "تقوية الهوية القبطية",
    biography: "قوى الهوية القبطية وحافظ على التراث.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Theophilus II",
    arabicName: "ثاوفيلس الثاني",
    orderNumber: 60,
    startYear: 952,
    endYear: 956,
    era: "العصر الإسلامي",
    contributions: "قيادة حكيمة في فترة قصيرة",
    biography: "قاد بحكمة رغم قصر فترة البطريركية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Mena II",
    arabicName: "مينا الثاني",
    orderNumber: 61,
    startYear: 956,
    endYear: 974,
    era: "العصر الإسلامي",
    contributions: "تطوير العلاقات مع السلطة",
    biography: "طور العلاقات مع السلطة وحافظ على حقوق الأقباط.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Abraham",
    arabicName: "إبرآم",
    orderNumber: 62,
    startYear: 975,
    endYear: 978,
    era: "العصر الإسلامي",
    contributions: "إدارة مؤقتة للكنيسة",
    biography: "أدار الكنيسة بكفاءة في فترة انتقالية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Philotheus",
    arabicName: "فيلوثاؤس",
    orderNumber: 63,
    startYear: 979,
    endYear: 1003,
    era: "العصر الإسلامي",
    contributions: "تطوير الأدب القبطي",
    biography: "طور الأدب القبطي وأثرى الثقافة الكنسية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Zacharias",
    arabicName: "زخارياس",
    orderNumber: 64,
    startYear: 1004,
    endYear: 1032,
    era: "العصر الإسلامي",
    contributions: "مواجهة الاضطهاد الحاكمي",
    biography: "واجه اضطهاد الحاكم بأمر الله وحافظ على الكنيسة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Shenouda II",
    arabicName: "شنوده الثاني",
    orderNumber: 65,
    startYear: 1032,
    endYear: 1046,
    era: "العصر الإسلامي",
    contributions: "إعادة بناء الكنيسة",
    biography: "أعاد بناء الكنيسة بعد اضطهاد الحاكم.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Christodoulus",
    arabicName: "كريستوذولوس",
    orderNumber: 66,
    startYear: 1047,
    endYear: 1077,
    era: "العصر الإسلامي",
    contributions: "تقوية الكنيسة وتوسيعها",
    biography: "قوى الكنيسة ووسع انتشارها في مصر.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Cyril II",
    arabicName: "كيرلس الثاني",
    orderNumber: 67,
    startYear: 1078,
    endYear: 1092,
    era: "العصر الإسلامي",
    contributions: "إحياء التراث الكيرلسي",
    biography: "أحيا التراث الكيرلسي وطور التعليم اللاهوتي.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Michael II",
    arabicName: "ميخائيل الثاني",
    orderNumber: 68,
    startYear: 1092,
    endYear: 1102,
    era: "العصر الإسلامي",
    contributions: "تطوير الإدارة الكنسية",
    biography: "طور الإدارة الكنسية ونظم شؤون الأساقفة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Macarius II",
    arabicName: "مكاريوس الثاني",
    orderNumber: 69,
    startYear: 1102,
    endYear: 1128,
    era: "العصر الإسلامي",
    contributions: "تقوية العلاقات مع الأديرة",
    biography: "قوى العلاقات مع الأديرة وطور الحياة الرهبانية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel II",
    arabicName: "غبريال الثاني",
    orderNumber: 70,
    startYear: 1131,
    endYear: 1145,
    era: "العصر الإسلامي",
    contributions: "مواجهة التحديات الصليبية",
    biography: "واجه تحديات الحروب الصليبية وحافظ على الكنيسة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Michael III",
    arabicName: "ميخائيل الثالث",
    orderNumber: 71,
    startYear: 1145,
    endYear: 1146,
    era: "العصر الإسلامي",
    contributions: "قيادة قصيرة المدى",
    biography: "قاد الكنيسة لفترة قصيرة جداً.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John V",
    arabicName: "يوأنس الخامس",
    orderNumber: 72,
    startYear: 1147,
    endYear: 1166,
    era: "العصر الإسلامي",
    contributions: "تطوير العلاقات الدولية",
    biography: "طور العلاقات الدولية للكنيسة مع الكنائس الأخرى.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Mark III",
    arabicName: "مرقس الثالث",
    orderNumber: 73,
    startYear: 1166,
    endYear: 1189,
    era: "العصر الإسلامي",
    contributions: "تقوية الهوية القبطية",
    biography: "قوى الهوية القبطية في عصر صلاح الدين الأيوبي.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John VI",
    arabicName: "يوأنس السادس",
    orderNumber: 74,
    startYear: 1189,
    endYear: 1216,
    era: "العصر الإسلامي",
    contributions: "الحفاظ على التراث",
    biography: "حافظ على التراث القبطي في العصر الأيوبي.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Cyril III",
    arabicName: "كيرلس الثالث",
    orderNumber: 75,
    startYear: 1235,
    endYear: 1243,
    era: "العصر الإسلامي",
    contributions: "إحياء التراث اللاهوتي",
    biography: "أحيا التراث اللاهوتي القبطي وطور التعليم.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Athanasius III",
    arabicName: "أثناسيوس الثالث",
    orderNumber: 76,
    startYear: 1250,
    endYear: 1261,
    era: "العصر الإسلامي",
    contributions: "مواجهة التحديات المملوكية",
    biography: "واجه تحديات العصر المملوكي الجديد.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel III",
    arabicName: "غبريال الثالث",
    orderNumber: 77,
    startYear: 1268,
    endYear: 1271,
    era: "العصر الإسلامي",
    contributions: "قيادة في فترة انتقالية",
    biography: "قاد الكنيسة في فترة انتقالية صعبة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John VII",
    arabicName: "يوأنس السابع",
    orderNumber: 78,
    startYear: 1271,
    endYear: 1293,
    era: "العصر الإسلامي",
    contributions: "تطوير العلاقات مع المماليك",
    biography: "طور العلاقات مع السلطة المملوكية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Theodosius II",
    arabicName: "ثيودوسيوس الثاني",
    orderNumber: 79,
    startYear: 1294,
    endYear: 1300,
    era: "العصر الإسلامي",
    contributions: "الحفاظ على الاستقرار",
    biography: "حافظ على الاستقرار في نهاية القرن الثالث عشر.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John VIII",
    arabicName: "يوأنس الثامن",
    orderNumber: 80,
    startYear: 1300,
    endYear: 1320,
    era: "العصر الإسلامي",
    contributions: "تقوية الكنيسة في القرن الرابع عشر",
    biography: "قوى الكنيسة في مطلع القرن الرابع عشر.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John IX",
    arabicName: "يوأنس التاسع",
    orderNumber: 81,
    startYear: 1320,
    endYear: 1327,
    era: "العصر الإسلامي",
    contributions: "مواصلة تطوير الكنيسة",
    biography: "واصل تطوير الكنيسة وتقوية أسسها.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Benjamin II",
    arabicName: "بنيامين الثاني",
    orderNumber: 82,
    startYear: 1327,
    endYear: 1339,
    era: "العصر الإسلامي",
    contributions: "إحياء تراث بنيامين الأول",
    biography: "أحيا تراث بنيامين الأول وطور العلاقات.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Peter V",
    arabicName: "بطرس الخامس",
    orderNumber: 83,
    startYear: 1340,
    endYear: 1348,
    era: "العصر الإسلامي",
    contributions: "مواجهة تحديات الطاعون",
    biography: "واجه تحديات الطاعون الأسود وحافظ على الكنيسة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Mark IV",
    arabicName: "مرقس الرابع",
    orderNumber: 84,
    startYear: 1349,
    endYear: 1363,
    era: "العصر الإسلامي",
    contributions: "إعادة بناء ما دمره الطاعون",
    biography: "أعاد بناء ما دمره الطاعون وقوى الكنيسة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John X",
    arabicName: "يوأنس العاشر",
    orderNumber: 85,
    startYear: 1363,
    endYear: 1369,
    era: "العصر الإسلامي",
    contributions: "تطوير الإدارة",
    biography: "طور الإدارة الكنسية وحسن التنظيم.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel IV",
    arabicName: "غبريال الرابع",
    orderNumber: 86,
    startYear: 1370,
    endYear: 1378,
    era: "العصر الإسلامي",
    contributions: "تقوية العلاقات الخارجية",
    biography: "قوى العلاقات الخارجية للكنيسة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Matthew I",
    arabicName: "متاؤس الأول",
    orderNumber: 87,
    startYear: 1378,
    endYear: 1408,
    era: "العصر الإسلامي",
    contributions: "قيادة طويلة ومستقرة",
    biography: "قاد الكنيسة لفترة طويلة بحكمة واستقرار.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel V",
    arabicName: "غبريال الخامس",
    orderNumber: 88,
    startYear: 1409,
    endYear: 1427,
    era: "العصر الإسلامي",
    contributions: "تطوير التعليم الكنسي",
    biography: "طور التعليم الكنسي ونشر المعرفة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John XI",
    arabicName: "يوأنس الحادي عشر",
    orderNumber: 89,
    startYear: 1427,
    endYear: 1452,
    era: "العصر الإسلامي",
    contributions: "مواجهة نهاية العصر المملوكي",
    biography: "قاد الكنيسة في نهاية العصر المملوكي.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Matthew II",
    arabicName: "متاؤس الثاني",
    orderNumber: 90,
    startYear: 1452,
    endYear: 1465,
    era: "العصر الإسلامي",
    contributions: "التحضير للعصر العثماني",
    biography: "حضر الكنيسة لاستقبال العصر العثماني.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel VI",
    arabicName: "غبريال السادس",
    orderNumber: 91,
    startYear: 1466,
    endYear: 1475,
    era: "العصر الإسلامي",
    contributions: "بداية التعامل مع العثمانيين",
    biography: "بدأ التعامل مع القوة العثمانية الصاعدة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Michael IV",
    arabicName: "ميخائيل الرابع",
    orderNumber: 92,
    startYear: 1476,
    endYear: 1478,
    era: "العصر العثماني",
    contributions: "انتقال إلى العصر العثماني",
    biography: "قاد الانتقال إلى العصر العثماني.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John XII",
    arabicName: "يوأنس الثاني عشر",
    orderNumber: 93,
    startYear: 1480,
    endYear: 1482,
    era: "العصر العثماني",
    contributions: "تأسيس العلاقات العثمانية",
    biography: "أسس العلاقات مع السلطة العثمانية الجديدة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John XIII",
    arabicName: "يوأنس الثالث عشر",
    orderNumber: 94,
    startYear: 1484,
    endYear: 1524,
    era: "العصر العثماني",
    contributions: "ترسيخ النظام العثماني",
    biography: "رسخ النظام الجديد تحت الحكم العثماني.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel VII",
    arabicName: "غبريال السابع",
    orderNumber: 95,
    startYear: 1525,
    endYear: 1568,
    era: "العصر العثماني",
    contributions: "تطوير النظام الملي",
    biography: "طور النظام الملي تحت الحكم العثماني.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John XIV",
    arabicName: "يوأنس الرابع عشر",
    orderNumber: 96,
    startYear: 1571,
    endYear: 1585,
    era: "العصر العثماني",
    contributions: "تقوية الهوية القبطية",
    biography: "قوى الهوية القبطية في العصر العثماني.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Gabriel VIII",
    arabicName: "غبريال الثامن",
    orderNumber: 97,
    startYear: 1586,
    endYear: 1601,
    era: "العصر العثماني",
    contributions: "تطوير الإدارة الكنسية",
    biography: "طور الإدارة الكنسية في النظام العثماني.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Mark V",
    arabicName: "مرقس الخامس",
    orderNumber: 98,
    startYear: 1602,
    endYear: 1618,
    era: "العصر العثماني",
    contributions: "تقوية العلاقات مع الأديرة",
    biography: "قوى العلاقات مع الأديرة وطور الرهبنة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John XV",
    arabicName: "يوأنس الخامس عشر",
    orderNumber: 99,
    startYear: 1619,
    endYear: 1629,
    era: "العصر العثماني",
    contributions: "مواجهة التحديات الاقتصادية",
    biography: "واجه التحديات الاقتصادية بحكمة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Matthew III",
    arabicName: "متاؤس الثالث",
    orderNumber: 100,
    startYear: 1631,
    endYear: 1645,
    era: "العصر العثماني",
    contributions: "تطوير التعليم",
    biography: "طور التعليم الكنسي ونشر المعرفة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Mark VI",
    arabicName: "مرقس السادس",
    orderNumber: 101,
    startYear: 1645,
    endYear: 1660,
    era: "العصر العثماني",
    contributions: "تقوية الكنيسة",
    biography: "قوى الكنيسة وطور أنظمتها.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Matthew IV",
    arabicName: "متاؤس الرابع",
    orderNumber: 102,
    startYear: 1660,
    endYear: 1675,
    era: "العصر العثماني",
    contributions: "الحفاظ على التراث",
    biography: "حافظ على التراث القبطي وطوره.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John XVI",
    arabicName: "يوأنس السادس عشر",
    orderNumber: 103,
    startYear: 1676,
    endYear: 1718,
    era: "العصر العثماني",
    contributions: "قيادة طويلة ومستقرة",
    biography: "قاد الكنيسة لفترة طويلة ومستقرة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Peter VI",
    arabicName: "بطرس السادس",
    orderNumber: 104,
    startYear: 1718,
    endYear: 1726,
    era: "العصر العثماني",
    contributions: "تطوير العلاقات",
    biography: "طور العلاقات مع السلطات والمجتمع.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John XVII",
    arabicName: "يوأنس السابع عشر",
    orderNumber: 105,
    startYear: 1727,
    endYear: 1745,
    era: "العصر العثماني",
    contributions: "تقوية الإدارة",
    biography: "قوى الإدارة الكنسية وحسن التنظيم.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Mark VII",
    arabicName: "مرقس السابع",
    orderNumber: 106,
    startYear: 1745,
    endYear: 1769,
    era: "العصر العثماني",
    contributions: "مواجهة تحديات القرن الثامن عشر",
    biography: "واجه تحديات القرن الثامن عشر بحكمة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John XVIII",
    arabicName: "يوأنس الثامن عشر",
    orderNumber: 107,
    startYear: 1769,
    endYear: 1796,
    era: "العصر العثماني",
    contributions: "مواجهة الحملة الفرنسية",
    biography: "واجه تحديات الحملة الفرنسية على مصر.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Mark VIII",
    arabicName: "مرقس الثامن",
    orderNumber: 108,
    startYear: 1796,
    endYear: 1809,
    era: "العصر الحديث",
    contributions: "بداية العصر الحديث",
    biography: "قاد الكنيسة في بداية العصر الحديث.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Peter VII",
    arabicName: "بطرس السابع",
    orderNumber: 109,
    startYear: 1809,
    endYear: 1852,
    era: "العصر الحديث",
    contributions: "مواجهة تحديات محمد علي",
    biography: "واجه تحديات عصر محمد علي باشا.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Cyril IV",
    arabicName: "كيرلس الرابع",
    orderNumber: 110,
    startYear: 1854,
    endYear: 1861,
    era: "العصر الحديث",
    contributions: "أبو الإصلاح، تطوير التعليم",
    biography: "لُقب بأبو الإصلاح، طور التعليم وأسس المدارس.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Demetrius II",
    arabicName: "ديمتريوس الثاني",
    orderNumber: 111,
    startYear: 1862,
    endYear: 1870,
    era: "العصر الحديث",
    contributions: "مواصلة الإصلاحات",
    biography: "واصل إصلاحات كيرلس الرابع وطور الكنيسة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Cyril V",
    arabicName: "كيرلس الخامس",
    orderNumber: 112,
    startYear: 1874,
    endYear: 1927,
    era: "العصر الحديث",
    contributions: "قيادة طويلة، مواجهة الاحتلال البريطاني",
    biography: "قاد الكنيسة لأكثر من 50 عاماً وواجه الاحتلال البريطاني.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope John XIX",
    arabicName: "يوأنس التاسع عشر",
    orderNumber: 113,
    startYear: 1928,
    endYear: 1942,
    era: "العصر الحديث",
    contributions: "قيادة الكنيسة في القرن العشرين",
    biography: "قاد الكنيسة في النصف الأول من القرن العشرين.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Macarius III",
    arabicName: "مكاريوس الثالث",
    orderNumber: 114,
    startYear: 1944,
    endYear: 1945,
    era: "العصر الحديث",
    contributions: "قيادة قصيرة لكن مؤثرة",
    biography: "حكم لفترة قصيرة جداً لكن ترك أثراً إيجابياً.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Yusab II",
    arabicName: "يوساب الثاني",
    orderNumber: 115,
    startYear: 1946,
    endYear: 1956,
    era: "العصر الحديث",
    contributions: "قيادة الكنيسة بعد الحرب العالمية",
    biography: "قاد الكنيسة في فترة ما بعد الحرب العالمية الثانية.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Cyril VI",
    arabicName: "كيرلس السادس",
    orderNumber: 116,
    startYear: 1959,
    endYear: 1971,
    era: "العصر الحديث",
    contributions: "أحدث نهضة روحية ورهبانية كبيرة في الكنيسة",
    biography: "أحدث نهضة روحية ورهبانية كبيرة في الكنيسة. قُدس كقديس وأحيا الحياة الرهبانية في الأديرة.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Shenouda III",
    arabicName: "شنوده الثالث",
    orderNumber: 117,
    startYear: 1971,
    endYear: 2012,
    era: "العصر الحديث",
    contributions: "المعلم العظيم، توسيع الخدمة في المهجر، إحياء الرهبنة",
    biography: "لُقب بالمعلم العظيم لغزارة تعليمه وكتاباته. أحيا الحياة الرهبانية وأسس كنائس كثيرة في المهجر.",
    heresiesFought: JSON.stringify([]),
    active: true
  },
  {
    name: "Pope Tawadros II",
    arabicName: "تواضروس الثاني",
    orderNumber: 118,
    startYear: 2012,
    endYear: null,
    era: "العصر الحديث",
    contributions: "قيادة الكنيسة في القرن الحادي والعشرين، بناء العاصمة الإدارية الجديدة، مواجهة التحديات الحديثة",
    biography: "البابا الحالي للكنيسة القبطية الأرثوذكسية منذ 2012. بنى كاتدرائية ميلاد المسيح في العاصمة الإدارية الجديدة، وطور الكنيسة لتواكب تحديات القرن الحادي والعشرين.",
    heresiesFought: JSON.stringify([]),
    active: true
  }
];