export const patriarchNamesArabic: Record<string, string> = {
  "Saint Mark the Evangelist": "القديس مرقس الرسول",
  "Anianus": "حنانيا",
  "Avilius": "أبيليوس",
  "Kedron": "كيدرون",
  "Justus": "يسطس",
  "Eumenes": "أومانيوس",
  "Markianos": "مرقيانوس",
  "Celadion": "كيلاديون",
  "Agrippinus": "أغريبينوس",
  "Julian": "يوليانوس",
  "Demetrius": "ديمتريوس",
  "Heraclas": "هيراكلاس",
  "Dionysius": "ديونيسيوس",
  "Maximus": "مكسيموس",
  "Theonas": "ثاؤناس",
  "Peter I": "بطرس الأول",
  "Achillas": "أخيلاس",
  "Alexander": "الكسندروس",
  "Athanasius": "أثناسيوس الرسولي",
  "Peter II": "بطرس الثاني",
  "Timothy": "تيموثاوس",
  "Theophilus": "ثاؤفيلوس",
  "Cyril": "كيرلس الكبير",
  "Dioscorus": "ديسقوروس",
  "Timothy Aelurus": "تيموثاوس الثاني",
  "Peter III": "بطرس الثالث",
  "Athanasius II": "أثناسيوس الثاني",
  "John I": "يوحنا الأول",
  "John II": "يوحنا الثاني",
  "Dioscorus II": "ديسقوروس الثاني",
  "Timothy III": "تيموثاوس الثالث",
  "Theodosius": "ثيؤدوسيوس",
  "Peter IV": "بطرس الرابع",
  "Damian": "داميان",
  "Anastasius": "أنسطاسيوس",
  "Andronicus": "أندرونيكوس",
  "Benjamin I": "بنيامين الأول",
  "Agathon": "أغاثون",
  "John III": "يوحنا الثالث",
  "Isaac": "إسحق",
  "Simon I": "سيمون الأول",
  "Alexander II": "الكسندروس الثاني",
  "Cosmas I": "قزمان الأول",
  "Theodore": "ثيؤدوروس",
  "Michael I": "ميخائيل الأول",
  "John IV": "يوحنا الرابع",
  "Mark II": "مرقس الثاني",
  "Jacob": "يعقوب",
  "Simon II": "سيمون الثاني",
  "Joseph I": "يوسف الأول",
  "Michael II": "ميخائيل الثاني",
  "Cosmas II": "قزمان الثاني",
  "Michael III": "ميخائيل الثالث",
  "Macarius I": "مكاريوس الأول",
  "Gabriel I": "غبريال الأول",
  "Michael IV": "ميخائيل الرابع",
  "John V": "يوحنا الخامس",
  "Mark III": "مرقس الثالث",
  "John VI": "يوحنا السادس",
  "Cyril II": "كيرلس الثاني",
  "Michael V": "ميخائيل الخامس",
  "Macarius II": "مكاريوس الثاني",
  "Gabriel II": "غبريال الثاني",
  "Michael VI": "ميخائيل السادس",
  "John VII": "يوحنا السابع",
  "Cyril III": "كيرلس الثالث",
  "David I": "داود الأول",
  "Christodoulus": "خريستوذولس",
  "Cyril IV": "كيرلس الرابع",
  "Demetrius II": "ديمتريوس الثاني",
  "Macarius III": "مكاريوس الثالث",
  "Cyril V": "كيرلس الخامس",
  "John VIII": "يوحنا الثامن",
  "Cyril VI": "كيرلس السادس",
  "Shenouda III": "شنودة الثالث",
  "Tawadros II": "تواضروس الثاني"
};

export function getArabicPatriarchName(englishName: string): string {
  return patriarchNamesArabic[englishName] || englishName;
}

export const heresiesArabic: Record<string, string> = {
  "Arianism": "الآريوسية",
  "Nestorianism": "النسطورية",
  "Monophysitism": "المونوفيزية",
  "Monothelitism": "المونوثيليتية",
  "Iconoclasm": "محاربة الأيقونات",
  "Apollinarianism": "الأبولينارية",
  "Donatism": "الدوناتية",
  "Pelagianism": "البيلاجية",
  "Sabellianism": "السابيلية",
  "Modalism": "الموداليزم",
  "Docetism": "الدوسيتية",
  "Gnosticism": "الغنوصية",
  "Marcionism": "المارسيونية",
  "Manichaeism": "الأريوسية",
  "Origenism": "الأوريجينية",
  "Macedonianism": "المقدونية",
  "Pneumatomachi": "محاربي الروح",
  "Chalcedonian": "الخلقيدونية",
  "Melkite": "الملكية",
  "Monothelite": "المونوثيليتية",
  "Monoenergism": "المونوإنرجيزم",
  "Adoptionism": "التبني",
  "Patripassianism": "معاناة الآب",
  "Subordinationism": "التبعية",
  "Tritheism": "التثليث الثلاثي",
  "Theopaschitism": "معاناة الله",
  "Crypto-Arianism": "الآريوسية المخفية",
  "Semi-Arianism": "شبه الآريوسية",
  "Anomoeanism": "الأنوموية",
  "Homoianism": "الهوموية",
  "Eunomianism": "الأونومية"
};

export function getArabicHeresyName(heresy: string): string {
  const arabicNames: Record<string, string> = {
    'الآريوسية': 'الآريوسية',
    'Arianism': 'الآريوسية',
    'النسطورية': 'النسطورية', 
    'Nestorianism': 'النسطورية',
    'المونوفيزيتية': 'المونوفيزيتية',
    'Monophysitism': 'المونوفيزيتية',
    'تحطيم الأيقونات': 'تحطيم الأيقونات',
    'Iconoclasm': 'تحطيم الأيقونات',
    'الدوناتية': 'الدوناتية',
    'Donatism': 'الدوناتية',
    'البيلاجية': 'البيلاجية',
    'Pelagianism': 'البيلاجية',
    'الأبوليناريوسية': 'الأبوليناريوسية',
    'Apollinarianism': 'الأبوليناريوسية',
    'المقدونية': 'المقدونية',
    'Macedonianism': 'المقدونية',
    'الغنوسية': 'الغنوسية',
    'Gnosticism': 'الغنوسية',
    'المرقيونية': 'المرقيونية',
    'Marcionism': 'المرقيونية',
    'المونتانية': 'المونتانية',
    'Montanism': 'المونتانية',
    'السابيلية': 'السابيلية',
    'Sabellianism': 'السابيلية',
    'المودالية': 'المودالية',
    'Modalisms': 'المودالية',
    'الأوطاخية': 'الأوطاخية',
    'Eutychianism': 'الأوطاخية',
    'الخلقيدونية': 'الخلقيدونية',
    'Chalcedonianism': 'الخلقيدونية'
  };

  return arabicNames[heresy] || heresy;
}